### ISSUE TITLE
BUG: Frame transclusions not working (2.5.0)

### ISSUE THREAD

**Issue by alkuzman** [zsviczian/obsidian-excalidraw-plugin#2028] opened 2024-09-19 06:54 UTC
### Have you searched for existing issues (including closed ones)?

- [X] Yes, I have searched the existing issues.

### Does this bug persist in a new vault with only Excalidraw installed?

- [X] Yes, I have verified the issue persists.

### Your environment

SYSTEM INFO:
	Obsidian version: v1.6.7
	Installer version: v1.6.7
	Operating system: #1 SMP PREEMPT_DYNAMIC Sun Sep  8 17:23:55 UTC 2024 6.10.9-200.fc40.x86_64
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 2
	Plugins enabled: 2
		1: Excalidraw v2.5.0
		2: vConsole v1.0.2

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

### Describe the bug

First, I have tested and checked that all links point to existing files and the issue is present both on desktop and mobile.

Since the last update, the frame embeddings are not working.
1. Copying and pasting a frame link into another drawing does not work.
2. Old frame transclusions do not render but the links work (clicking on them will redirect to the correct drawing).
3. Some of the latex formulas are also not rendered.

Note: If I remove the frame reference from in the editor, the image is rendered properly.

Strange behavior 1: In a few places, the frames are rendered correctly; I'm not sure why. I cannot reproduce it because of 1. 
Strange behavior 2: In 2 different MOCs I have embedded the same icon (an excalidraw icon) without any frame. In one MOC the icon is rendered correctly but not in the other. If embeddings are rendered sequentially, it might be because another embedding rendering failed and the code won't continue to render the remaining images. Just guessing :)

### Steps to reproduce

1. Copy the frame link
2. Try to paste the link into another drawing (This won't work)

### Expected behavior

Frame embeddings should render as expected.

### Additional context

![image](https://github.com/user-attachments/assets/7ab6c92f-b246-4092-b42f-1fd008f27c7f)
![image](https://github.com/user-attachments/assets/6bdbe908-56c1-4fc7-b950-ec71753512f1)

**Comment by zsviczian** [comment] 2024-09-19 17:20
hm... I cannot reproduce.

**Comment by zsviczian** [comment] 2024-09-19 17:23
Do all your frames include latex equations?... I am able to reproduce if the frame includes an equation.

note, this is why I don't like to develop features I do not myself use. I never write LaTeX equations, thus never spot that something is broken...

**Comment by zsviczian** [comment] 2024-09-19 17:41
The page breaks if there are any LaTeX equations on the source page regardless of them being included in the frame or not...

Will release a fix in the beta channel today

**Comment by zsviczian** [comment] 2024-09-19 18:02
fixed in 2.5.1-beta-1

**Closed by zsviczian** 2024-09-19 18:02 UTC
