### ISSUE TITLE
The Excalidraw pane is still persist, when try to delete it

### ISSUE THREAD

**Issue by jokysatria** [zsviczian/obsidian-excalidraw-plugin#37] opened 2021-04-29 23:15 UTC
**Describe the bug**
I try to delete Excalidraw file from more option drop down, but after delete it, the pane is still persist

**To Reproduce**

https://user-images.githubusercontent.com/69371378/116629307-1a2a8d80-a97b-11eb-8f5d-678296603a8f.mp4

Step to reproduce (What I do in this video) :
1. Open Excalidraw
2. Try to delete it by using pane option. After deleting the Excalidraw pane still presist (what expected: it's closed as other panes do)
3. Try to look that excalidraw filein the explorer, but I can't found it.
4. When I close the pane, the file suddenly appears! (what expected: it doesn't show, since it's deleted)
5. Then I try to open it again, by clicking the file in the Explorer
6. Open pane more option, and click navigate the file (and it shows correctly)
7. Try to delete the Excalidraw, by using pane more option. And it's deleted, but the pane is still presist.
8. But now when I close the pane, it doesn't appear again in Explorer.

**Desktop (please complete the following information):**
 - OS: Windows 10 2h20 64x
 - Obsidian version: 0.11.13.
 - Obsidian installer version: 0.11.9.

**Comment by zsviczian** [comment] 2021-04-30 04:29
Thanks! Will try to address this in a next update.
As a workaround you can delete drawings by right clicking the file in the file explorer and choosing delete.

**Comment by zsviczian** [comment] 2021-05-02 19:52
solved in 1.0.8. Will be released in the next couple of days.

**Comment by zsviczian** [comment] 2021-05-06 21:35
Here's 1.0.8-test3. It resolves this issue as well. 
https://github.com/zsviczian/obsidian-excalidraw-plugin/releases/tag/1.0.8-test3

**Comment by jokysatria** [comment] 2021-05-07 03:11
Thank you! 
When I tried the pane is closed. But the file is not deleted.
Somehow, after I click option "reveal in navigation", I can delete the file completely.


https://user-images.githubusercontent.com/69371378/117392590-92b1c100-af1c-11eb-9719-4e2c8cf68898.mp4

**Comment by zsviczian** [comment] 2021-05-07 05:35
did you restart obsidian after copying the downloaded 1.0.8-test3 files to the .osidian/plugins/obsidian-excalidraw-plugin/ folder?

**Comment by jokysatria** [comment] 2021-05-07 11:54
Sorry I didn't restart My Obsidian (I just reloaded it from community plugin settings). And yes, the version was still 1.0.7.
Recently I repeat the steps as your lists. And to delete the file, I need to delete it twice.

![image](https://user-images.githubusercontent.com/69371378/117445959-9a498800-af65-11eb-8c4e-a271d0da00f5.png)


https://user-images.githubusercontent.com/69371378/117445875-77b76f00-af65-11eb-8069-cb44c2108723.mp4

**Comment by zsviczian** [comment] 2021-05-07 13:43
Thanks! I will double check what the issue might be. I think it is due to another fix I implemented in the last minute to improve saving of the file.

**Comment by zsviczian** [comment] 2021-05-07 16:05
Hm. I am unable to reproduce the error. I even installed Obsidian Tabs. What operating system / environment are you using?

**Comment by zsviczian** [comment] 2021-05-07 18:36
1.0.8 release solves this

**Closed by zsviczian** 2021-05-07 18:36 UTC
Labels: bug

**Comment by jokysatria** [comment] 2021-05-07 21:40
Can confirm, it's solved in the 1.0.8, thank you so much!
