### ISSUE TITLE
Error in loading Mermaid within Excalidraw

### ISSUE THREAD

**Issue by sutrisno00** [zsviczian/obsidian-excalidraw-plugin#1503] opened 2023-12-12 23:15 UTC
**Your environment**
SYSTEM INFO:
	Obsidian version: v1.5.1
	Installer version: v1.4.13
	Operating system: Darwin Kernel Version 22.6.0: Wed Oct  4 21:25:26 PDT 2023; root:xnu-8796.141.3.701.17~4/RELEASE_X86_64 22.6.0
	Login status: logged in
	Catalyst license: supporter
	Insider build toggle: on
	Live preview: on
	Base theme: dark
	Community theme: Minimal v7.4.2
	Snippets enabled: 4
	Restricted mode: off
	Plugins installed: 66
	Plugins enabled: 39
		1: Natural Language Dates v0.6.2
		2: Emoji Toolbar v0.4.1
		3: Kanban v1.5.3
		4: Workspaces Plus v0.3.3
		5: Link Archive v0.2.0
		6: Quick Latex for Obsidian v2.6.3
		7: Breadcrumbs v3.6.4
		8: Highlightr v1.2.2
		9: Minimal Theme Settings v7.3.1
		10: Style Settings v1.0.7
		11: Footnote Shortcut v0.1.3
		12: Sortable v0.3.1
		13: Simple Embeds v1.15.0
		14: Timelines v0.3.2
		15: Obsidian Columns v1.5.2
		16: ExcaliBrain v0.2.11
		17: Release Timeline v1.2.0
		18: Custom Frames v2.4.6
		19: Pandoc Plugin v0.4.1
		20: Text Extractor v0.4.8
		21: Omnisearch v1.19.0
		22: Iconize v2.8.0
		23: Obsidian Tabs v1.0.7
		24: Obsidian Leaflet v6.0.1
		25: Hover Editor v0.11.15
		26: ibook v2.0.12
		27: Wrap with shortcuts v1.3.0
		28: Tag Wrangler v0.6.1
		29: obsidian markmind v1.8.7
		30: Templater v2.0.0
		31: Floating Search v3.4.5
		32: Global Search and Replace v0.3.0
		33: Importer v1.5.6
		34: Local Images Plus v0.15.9
		35: Omnivore v1.8.1
		36: Dataview v0.5.64
		37: Hotkeys for templates v1.4.3
		38: Admonition v10.1.1
		39: Excalidraw v2.0.10

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Describe the bug**
Trying to embed mermaid diagram into Excalidraw using "Mermaid to Excalidraw". Preview Panel showing "Error ! - Cannot read properties of undefined (reading 'mermaidAPI')"

**To Reproduce**
1. Open Excalidraw
2. Click on the icon to invoke "Mermaid to Excalidraw"
3. See error above

**Expected behavior**
Able to see a preview from pre-format flowchart, but instead an error message in red.

**Screenshots**
<img width="990" alt="image" src="https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/94269130/361ff54c-aa1d-459b-8726-dc6ffb3bd3ce">

**Comment by zsviczian** [comment] 2023-12-17 11:53
I can't reproduce the issue. Can I ask you to try this in an empty test Vault with only Excalidraw installed?

**Comment by sutrisno00** [comment] 2023-12-18 03:21
Many thanks for looking into this, Zsolt. I have created a new vault with one note, and Excalidraw showing the same error. Below is the debug info. Please let me know if additional information / anything else I can 'test' to help in see the cause of the error.

SYSTEM INFO:
	Obsidian version: v1.5.2
	Installer version: v1.4.16
	Operating system: Darwin Kernel Version 22.6.0: Wed Oct  4 21:25:26 PDT 2023; root:xnu-8796.141.3.701.17~4/RELEASE_X86_64 22.6.0
	Login status: logged in
	Catalyst license: supporter
	Insider build toggle: on
	Live preview: on
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 1
	Plugins enabled: 1
		1: Excalidraw v2.0.10

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by sutrisno00** [comment] 2023-12-20 09:45
Interestingly, the mermaid preview doesn't load up on safari, but works fine as expected on another browser (Firefox). I am on Mac. Anything I should check or tinkle with ?

Appreciate any pointers. Thanks

**Comment by zsviczian** [comment] 2023-12-20 11:25
You are using Excalidraw.com ?
This GitHub is not for Excalidraw.com but for the Obsidian plugin.

https://github.com/excalidraw/excalidraw/issues

**Comment by zsviczian** [comment] 2023-12-20 15:18
so you are using Obsidian on an iPad?

**Comment by sutrisno00** [comment] 2023-12-20 23:52
Again, many many thanks, Zsolt.

1) No, I am using only on Mac (iMac and MacBook). I was trying it on the web version to see if anything amiss with my system because it show the same error loading inside obsidian on both my machines. Thanks for explaining the difference between Safari and Chrome. I didn't know that.

2) Regarding the installer version, I did as you suggested, that is download the installer  from Obsidian.md, and then hit check for updates. Mine reads 

Current version : v1.5.2
(Installer version : v1.4.16)

Are these the latest ?

My desktop version has older OS (v13 Ventura) and MacBook (v14 Sonoma).  Both with same version and same error.

Anything else I should check ?

**Comment by sutrisno00** [comment] 2024-01-06 03:08
Zsolt - miraculously it worked this morning. Unsure if it is because of the latest version of Excalidraw or I clean up the cache that is corrupting it (I delete the whole obsidian folder under Application Support - I am using iMac).

Want to take this opportunity to thank you for the tremendous work you put into Excalidraw for Obsidian.

**Comment by zsviczian** [comment] 2024-01-06 05:48
I am glad it works.
With software, I usually don't like miracles, because they often hide underlying problems. But I am glad this got resolved.

**Comment by sutrisno00** [comment] 2024-01-07 11:29
Indeed - the problem came back again and it seems only applicable only to non-main window, i.e. if I use a new window that is 'detached' from the main window, then there is problem. If I use the main window, then it is behaving as normal.

**Comment by zsviczian** [comment] 2024-01-07 14:55
This is very helpful. I will test. If this is the case then I know how to solve it.

**Comment by zsviczian** [comment] 2024-01-07 18:18
Great! solved it. Will be resolved in the next release.

**Closed by zsviczian** 2024-01-07 18:18 UTC
