### ISSUE TITLE
Why does it automatically go back to the previous step?

### ISSUE THREAD

**Issue by zhl111** [zsviczian/obsidian-excalidraw-plugin#296] opened 2021-12-10 07:54 UTC
This phenomenon occurs quite frequently when I make a file
![动画](https://user-images.githubusercontent.com/29135984/145537216-bf09157f-3b1c-4f80-a09a-50d973511c60.gif)

**Comment by zsviczian** [comment] 2021-12-10 08:25
This is a "feature". To avoid errors with Wiki links, after certain actions involving text elements, I clear the undo history.
I may revisit this design decision, however there was a complex set of dependencies, and at the time cutting the proverbial Gordian knot by clearing the undo history seemed like a fit for purpose approach.

**Comment by zhl111** [comment] 2021-12-10 08:38
It seems that this "feature" is not limited to test elements, but almost any action can be backtracked to the previous step

**Comment by zsviczian** [comment] 2021-12-10 09:28
I wonder what's going on in your case. I only clear the undo history in a very specific case, when you add a wiki link in a text element. The example you show above does not include a wiki link. 

I just tried to repeat your demo, and undo/redo works as expected for me. 

https://user-images.githubusercontent.com/14358394/145550759-d2701e13-a4b8-4e22-8658-ce2233e6557a.mp4

**Comment by zsviczian** [comment] 2021-12-10 09:31
ah... I am misunderstanding you. This is not about undo.
Do you have Excalidraw open in two windows with the same document?
Do you have Excalidraw open as a markdown document in another window?

**Comment by zhl111** [comment] 2021-12-10 13:19
just this
![image](https://user-images.githubusercontent.com/29135984/145580163-75eb1c4d-41fa-4fd2-b298-499ed19fc0f7.png)

**Comment by zsviczian** [comment] 2021-12-10 13:28
those embeds, are they different files, or sections of your excalidraw.markdown document?

**Comment by zhl111** [comment] 2021-12-10 16:11
All created in Excalidraw

**Comment by zsviczian** [comment] 2021-12-10 16:26
and are those markdown embeds?

**Comment by zhl111** [comment] 2021-12-10 17:24
nope。
[D2021-12-02 20.31.02.excalidraw.zip](https://github.com/zsviczian/obsidian-excalidraw-plugin/files/7694411/D2021-12-02.20.31.02.excalidraw.zip)
，

**Comment by zsviczian** [comment] 2021-12-10 17:38
hm... the file looks normal.
To be honest, at this point I have absolutely no idea why you are experiencing this, but I am committed to helping you find the root cause and to fix it, if the issue is with the Excalidraw plugin.

This looks as if the file is changed by another process in the background and Excalidraw is triggered to refresh the drawing.
I update open drawings when the file changes in the background (assuming a synchronized version of the file has arrived).

Do you have some synchronization running in the background? e.g. synch to github every x minutes? or something similar?
Can you try turning off all other plugins to see if that improves the situation, then turning other plugins on one by one until the issue reappears?

**Comment by zhl111** [comment] 2021-12-11 02:02
Yes, my files are in onedriver

**Comment by zsviczian** [comment] 2021-12-11 05:08
That makes sense. I am assuming MetaEdit modifies the Excalidraw markdown file in the background (when autosave triggers), which triggers Excalidraw to reload the drawing.

Can you send a screenshot of your MetaEdit settings?

I can do two things:
- add a setting to disable Excalidraw Autosave
- raise a ticket with MetaEdit to help fix the problem

**Comment by zhl111** [comment] 2021-12-11 05:35
Excalidraw Autosave is good, I choose to have metaedit fixed or not to use it
![image](https://user-images.githubusercontent.com/29135984/145665292-ba8730dd-230e-4822-8bfe-eccdc330a45b.png)

**Closed** 2021-12-23 19:19 UTC
Labels: Issue caused by other plugin
