### ISSUE TITLE
Embedded excalidraw dark mode previews have inverted colors

### ISSUE THREAD

**Issue by OfficerHalf** [zsviczian/obsidian-excalidraw-plugin#230] opened 2021-11-04 14:53 UTC
**Describe the bug**
Embedded excalidraw previews have inverted lightness values when the excalidraw drawing is set to dark mode.

**To Reproduce**
1. Embed an excalidraw drawing in a note, and switch to edit mode.
![image](https://user-images.githubusercontent.com/4851889/140336315-66d66eaa-54bf-4cb1-b39e-278f14853245.png)

2. Update the drawing to dark mode.
3. See inverted preview image.
![image](https://user-images.githubusercontent.com/4851889/140336261-3d3ef07f-d2e0-44db-b50a-1d0250e0e113.png)

**Expected behavior**
The drawing should render the same in light and dark mode (possibly with a different background color).

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Obsidian 0.12.19

**Additional context**
Seems like it's not inverting all the colors, just swapping the white value. This also may only apply to embedded images in the drawing.

**Comment by zsviczian** [comment] 2021-11-04 20:11
Thanks for raising this. I noticed it as well. I’ll see what I can do.

**Comment by HiRolla** [comment] 2021-11-05 20:18
I have inverted colors too but in different situation. 
I embed one drawing into another and some colors are displayed as if it would be the light mode enabled while I use the dark mode only.  
![image](https://user-images.githubusercontent.com/7746812/140573348-496c98b8-5109-4a20-a304-a976a7ed0788.png)

**Comment by zsviczian** [comment] 2021-11-05 21:13
Thanks for raising this!

Color inverting of embedded images is not very intelligent at the moment.
And unfortunately, as of right now, I am not sure I will be able to do much
to solve this issue. Your best bet is to experiment with export settings. Try
to play with turning on or off “Export image with background” and “Export
image with theme”. That may help.

**Comment by zsviczian** [comment] 2021-11-08 18:46
I believe the issue is resolved with 1.4.7.
@OfficerHalf , please set export options to export without theme
![image](https://user-images.githubusercontent.com/14358394/140799706-cf27b55b-4eff-460b-8e96-122f82f846ac.png)

**Comment by HiRolla** [comment] 2021-11-09 18:40
@zsviczian Thank you! It works great now!

**Comment by zsviczian** [comment] 2021-11-16 13:41
Add `filter="invert(93%) hue-rotate(180deg)"` to `<use>` tags where `<image>` mimeType is not svg+xml.

**Comment by zsviczian** [comment] 2021-11-21 15:02
I am releasing 1.4.11 a bit later today. That should fully resolve this issue.

**Closed by zsviczian** 2021-11-21 15:02 UTC
