### ISSUE TITLE
BUG: Unable to load obsidian excalidraw plugin on ipad 15.x or older (no issues on iPad 16.x and higher)

### ISSUE THREAD

**Issue by retiarylime** [zsviczian/obsidian-excalidraw-plugin#1525] opened 2023-12-30 01:15 UTC
**Your environment**

SYSTEM INFO:
	Operating system: ios 14.2 (Apple iPad)
	Obsidian version: 1.4.16 (114)
	API version: v1.4.16
	Login status: logged in
	Catalyst license: none
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Things v2.1.15
	Snippets enabled: 1
	Restricted mode: off
	Plugins installed: 13
	Plugins enabled: 5
		1: Advanced Tables v0.20.0
		2: Style Settings v1.0.7
		3: Hider v1.3.1
		4: Dataview v0.5.64
		5: Image Captions v1.1.0

**Describe the bug**
Unable to load obsidian excalidraw plugin on ipad.

**Screenshots**
![3E7C63B3-A320-421C-BE5C-24566CE88CE3](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/83970685/0961a5a6-de37-4575-884c-2dfffc381710)

**Comment by zsviczian** [comment] 2024-01-03 20:39
I've seen two reasons for this in the past. Older iOS version or company mobile device management causing problems.

**Comment by 1001ruchka** [comment] 2024-02-06 02:03
I have exactly the same error on iPadOS 15.7.2
Rollback with BRAT plugin to Excalidraw 2.0.17 helped.
The error occurs on 2.0.18 and higher.

**Comment by retiarylime** [comment] 2024-02-06 08:52
For ipados 14.2, the error starts at Excalidraw v1.9.21 and later. Excalidraw v1.9.20 and older has no problems.

**Comment by zsviczian** [comment] 2024-02-18 08:49
In 2.0.21 I am rebuilding all the packages with Node 18. I hope it will address compatibility with iPad OS 15.7.2, since the difference between 2.0.17 and 2.0.18 is a build change introduced by the Excalidraw package which drove me to experiment with build setups... until I managed to figure out how to get it work... long story short, I hope the issue with iPad OS 15 can be resolved with this rebuilding.
As for iPad OS 14.2 - I am afraid if 2.0.17 did not work for you, then 2.0.21 will not solve the problems either. I recommend upgrading to a newer OS version.
🫰that the rebuild will bring the desired result - else I don't have other ideas on how to debug and solve this. :(

**Comment by zsviczian** [comment] 2024-02-19 18:34
I just released 2.0.21 - which is a complete rebuild with an older version of Node. Can you test if 2.0.21 works for you?

**Comment by 1001ruchka** [comment] 2024-02-19 21:24
Test 2.0.21 on PadOS 15.7.2 - failed to load error

**Comment by zsviczian** [comment] 2024-02-19 21:35
That is unfortunate. I'll try to think of other solutions... but without
being able to reproduce and test, I see limited chance of success. Sorry
about that.

Can you not update your iPadOS?

**Comment by 1001ruchka** [comment] 2024-02-19 21:47
![1C1CA176-DB03-4EC8-B13C-8D4E9FCF674C](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/5934321/18850400-40cd-48c4-95fe-64d90826ac52)

**Comment by 1001ruchka** [comment] 2024-02-19 21:50
Similar problem:
https://forum.obsidian.md/t/plugin-failure-promisereactionjob-native-code-web-assembly-related/43392

**Comment by zsviczian** [comment] 2024-02-19 21:57
I got my hands on an old gen 6 ipad with iPadOS 15.5
I am able to reproduce the issue. Still not sure if I can do anything about it, but reproducing the error is the first step for sure...

**Comment by 1001ruchka** [comment] 2024-02-19 22:06
I have a 6th generation iPad. Theoretically it can be upgraded to 17.x, but practically it will kill it.

**Comment by zsviczian** [comment] 2024-02-19 22:20
So I can reproduce, that 2.0.17 works, 2.0.18 does not. This is a starting point. Now I can try to take things apart from what changed between 17 and 18... as said earlier the excalidraw.com package build process changed, which caused me lots of headache in the plugin... let's see if I can play back to what is making the difference. It is likely some transpiling of code and target javascript versions.

**Comment by zsviczian** [comment] 2024-02-19 22:24
ok. I have a suspicion. I am hopeful I'll get this resolved tomorrow. We'll see...

**Comment by zsviczian** [comment] 2024-02-20 22:58
so... took me 6+ hours of debugging and I found the root cause in the @excalidraw/laser_pointer component.
Unfortunately I don't have access to the source project, but I have a manual patch / fix I can apply. I hope the issue I raised will be addressed.

Today is too late in the evening... will release the fix tomorrow.

**Comment by zsviczian** [comment] 2024-02-21 17:50
I just released 2.0.22 which I tested on my old iPad running iOS 15.5.

Please let me know if this release has resolved the issue for you.

**Comment by 1001ruchka** [comment] 2024-02-22 03:58
> I just released 2.0.22 which I tested on my old iPad running iOS 15.5.

Hello! Tested it - everything works fine on iPadOS 15.7.2. Thank you!

**Comment by paulelms** [comment] 2024-02-22 04:29
This update has finally fixed the issue with the plugin loading on the Huawei Mate X3, thanks!

**Closed** 2024-02-22 06:54 UTC
