### ISSUE TITLE
Some elements of drawings are not saved (even when pressing save button)

### ISSUE THREAD

**Issue by KennyDenvers** [zsviczian/obsidian-excalidraw-plugin#497] opened 2022-03-03 16:30 UTC
Below is the description of another user from a different issue thread (loss of files) - but my problem corresponds to the issue described there. 
(Windows 11; Obsidian v0.13.28; Excalidraw 1.6.16)

When I draw Excalidraw drawings and switch to a different note and back I have observed several times that elements that I recently added are gone (have not been saved). I have now gone over to saving manually "all the time" (pressing the disk symbol) (which is not possible in full screen mode). Still, sometimes the disk button does not react - but either way it would of course be great if drawings would actually be saved in accordance with the settings for autosave (30 seconds - now changed to 15 seconds).

Still enjoying Excalidraw Obsidian plugin a lot - but somewhat frustrating having to redo work. Thanks!

***
I got this data loss problem too, no matter how many times I try to `Ctrl + S` or click the save icon on the drawing page，when I switch the document out and in, some elements in the drawing disappeared. The version of obsidian is v0.13.23 and obsidian-excalidraw is v1.6.3. 

And obsidian-excalidraw v1.6.5 still not works

_Originally posted by @FatsharkGo in https://github.com/zsviczian/obsidian-excalidraw-plugin/issues/401#issuecomment-1033292812_

**Comment by zsviczian** [comment] 2022-03-03 17:25
Are you using Excalidraw in compatibility mode or with markdown drawings?

**Comment by KennyDenvers** [comment] 2022-03-03 17:29
I am sorry - how would I know that? The file extension is .excalidraw if that helps.

**Comment by zsviczian** [comment] 2022-03-03 17:41
when the drawing is open, click the more options menu and see if "Open as Markdown" is visible
![image](https://user-images.githubusercontent.com/14358394/156620868-3dc24438-a16b-4f07-b9ed-16c3d7590349.png)


Also are you using Excalidraw (and in particular this drawing) on multiple devices, and how are you doing the synchronization?

**Comment by KennyDenvers** [comment] 2022-03-03 20:40
Yes, I can see "Open as Markdown" there.
I have created that one particular (most recent) drawing on my laptop and had only opened it there when the problem (not saving all elements) occurred. I do sync my vault to mobile devices - via Obsidian sync.

The red disk symbol has been "red" continuously for several hours now while I was drawing and also after I have stopped drawing in that particular drawing.

Thanks for your support!!!

**Comment by zsviczian** [comment] 2022-03-04 05:45
Hm… the continuous red is strange. And it stays red even if you press save? It seems as if autosave is turned off. Please confirm you have the toggle “on”.
![1C3F3399-9814-4D40-BC61-6F654CCA4C9D](https://user-images.githubusercontent.com/14358394/156706753-34af7fd8-772c-4735-9fca-78240a3cec7c.jpeg)

When this happens, could I ask you to check developer console to see if there are any error messages, and to send me a screenshot?

you can access developer console by pressing CTRL+SHIFT+i

**Comment by KennyDenvers** [comment] 2022-03-04 09:11
This is what my screen looks like with developer console accessed. Don't know what I should look for there:

![image](https://user-images.githubusercontent.com/90445513/156733592-e375ae96-90a0-4b6a-9af0-da44e40e166c.png)

Autosave is and has been enabled ...

![image](https://user-images.githubusercontent.com/90445513/156733917-3d739fa4-a3b7-44e2-b2a0-48ec0d7435a1.png)

A lot of my changes have not been saved. I have exported to .excalidraw during the process. Will see if I can import that file into my vault now. ;-)

Have a good day!

**Comment by KennyDenvers** [comment] 2022-03-04 09:16
![image](https://user-images.githubusercontent.com/90445513/156734660-af364bc5-a8bf-4c28-bd82-b08c156ee318.png)

This is what my screen looks like with developer console accessed. Don't know what I should look for there. I have restarted my computer (and Obsidian) - disk symbol now "clear". But a lot of my changes have not been saved. I have exported to .excalidraw during the process. Will see if I can import that file into my vault now. ;-)

Autosave is and has been enabled ...

![image](https://user-images.githubusercontent.com/90445513/156734892-e694b741-6fe9-4fff-94af-b659fd28980a.png)

Have a good day!

**Comment by zsviczian** [comment] 2022-03-04 09:31
Good that you did the export. I hope you have no data loss.

I would need you to switch over to the "console" tab and share the screenshot of that, but only, when you experience the problem, that "Save" never stops being red.

![image](https://user-images.githubusercontent.com/14358394/156736676-5c440098-431c-4e09-95df-47da957b1fa9.png)

**Comment by KennyDenvers** [comment] 2022-03-06 09:49
Ok, thanks!
- So I will watch out for that and get back to you with that "data" in case it happens again.
- Anything to do about the other (?) issue that it automatic save seems not to be working consistently? I understand that it is actually not regular procedure to press the disk button, but that changes should be saved automatically (every X seconds as selected in settings)

**Comment by zsviczian** [comment] 2022-03-06 14:09
I've done a bit of debugging and made a few improvements to autosave. It will be released later today as part of 1.6.17

**Comment by KennyDenvers** [comment] 2022-03-07 12:02
This is a screenshot of the "Console" view after the disk symbol stayed red. (After that I closed Obsidian, restarted and installed a couple of plugin updates):

![image](https://user-images.githubusercontent.com/90445513/157030785-5d4c22e9-50b7-4eba-82cd-d86c042ba59f.png)

**Comment by zsviczian** [comment] 2022-03-07 12:05
hm.. can you share the drawing this relates to?
I wonder about fontSize of null...

**Comment by KennyDenvers** [comment] 2022-03-07 13:56
I believe it was this (but font size null?  Don't know where I should have used that ...) (below). One other question - or maybe you can redirect me somewhere: What are the differences / pros vs. cons of .excalidraw or .md drawings?

[Drawing 2022-03-07 12.11.50.excalidraw.md](https://github.com/zsviczian/obsidian-excalidraw-plugin/files/8198161/Drawing.2022-03-07.12.11.50.excalidraw.md)

**Comment by zsviczian** [comment] 2022-03-07 19:57
Unfortunately I am unable to reproduce the error with this file.

By any chance do you remember what you did before the error message appeared? Looks like excalidraw was expecting a text element, but found nothing.

I've made some changes to excalidraw, adding some extra error handling to the saving/loading process. Can I ask you to unzip this [file.zip](https://github.com/zsviczian/obsidian-excalidraw-plugin/files/8200448/main.zip) and copy `main.js` to the `.obsidian/plugins/obsidian-excalidraw-plugin` folder in your vault and use it for couple of days? Let me know if you encounter any further issues.

**Comment by zsviczian** [comment] 2022-03-28 09:24
I've implemented an additional layer of error handling with 1.6.21.
I will close this issue. I hope the problem will not happen again, if it does, please open a new ticket so I can further investigate.

**Closed by zsviczian** 2022-03-28 09:24 UTC
