### ISSUE TITLE
FR: Improvement of Startup Time

### ISSUE THREAD

**Issue by DocVonJ** [zsviczian/obsidian-excalidraw-plugin#2068] opened 2024-10-17 12:31 UTC
### Is your feature request related to a problem? Please describe.

Obsidian start-up time breakdown

Obsidian version: v1.7.4
Installer version: v1.4.13
Operating system: Windows 10 Home 10.0.19045

- Total startup time: 8,660ms
- Initialization: 1,492ms
- Vault (149 files): 491ms
- Workspace (11 tabs, 0 deferred): 1,527ms
- Core plugins: 182ms
- Community plugins (8 active): 4,967ms
  - ---> **Excalidraw** (v2.3.0): **2,887ms** <---
  - DB Folder (v3.5.1): 710ms
  - Iconize (v2.14.3): 662ms
  - Kanban (v2.0.51): 267ms
  - Dataview (v0.5.67): 157ms
  - Tasks (v7.9.0): 151ms
  - Charts (v3.9.0): 89ms
  - Calendar (v1.5.10): 22ms

**Comment by zsviczian** [comment] 2024-10-18 19:58
I understand. It is, however, not a priority for me a this time. There are two reasons why Excalidraw loads slow:
- The package is very large (over 6MB compressed). Most of the startup time is decompressing and compiling the code for execution. I want to continue to stick to a 100% local configuration. Obsidian does not support splitting the package into smaller files, so there is not much I can do. 
- Fonts are all loaded to memory at startup. This is the smaller reason. I may need to do something about this since with increasing number of fonts, this is going to become an issue. However this is a complex problem and to be honest, I don't have the energy to deal with it.

**Comment by GitMyCode** [comment] 2024-10-22 03:27
Hello, I m curious too about the slow startup of this plugin.
Seem that they recently release a new api for plugin to take advantage of deferred
https://docs.obsidian.md/Plugins/Guides/Understanding+deferred+views

**Comment by zsviczian** [comment] 2024-10-22 06:25
Thanks! 
I've already implemented support for deferred views 1 month ago when they were published in the alpha channel. BTW, deferred views happen regardless of the plugin, its rather that the plugin needs to make sure it does not make the assumption that the view is loaded before the tab is actually active.

As said above, core of the issue is the size of the plugin... and that is because Obsidian does not support plugins deploying assets, it all must be in a single main.js.

That said, I deferred loading of fonts. As a result, 2.5.3 loads somewhat faster. On my desktop I see figures between 650ms and 1000ms. Which is a roughly 2x improvement.

**Comment by Sprocketer** [comment] 2024-10-23 12:15
@zsviczian Is there any chance you could have an alternative set of several packages which work together to form the whole plugin? Or would it be too difficult to get different plugin files to communicate with each other like in one single JS file?

**Comment by zsviczian** [comment] 2024-10-23 13:44
That is creative idea and maybe something I'll consider for the custom font sets like CJK... It is probably easier to download a second plugin then a zip file... However, I would rather the user community collectively put a bit of pressure on the Obsidian Devs to allow plugins to deploy assets instead of working on creative workarounds, as that would be the proper solution.

BTW - on my various devices Excalidraw loads in about 800ms (note I am on a newer beta version that includes some load time improvements)... I understand on lower powered machines this might be 2-3000ms. However, for me, these times are fully acceptable, I don't really see an issue that needs to be worked on.

**Comment by zsviczian** [comment] 2024-10-26 16:21
It seems I can fix... :)
2.6.0-beta-4 is down to between 100ms and 200ms startup time

You can test it using BRAT. I'd love to receive some feedback if it is working for you, or if it has created issues. I've made some significant changes to achieve this thus I am concerned to publish the change without deep enough testing.

I explain how to beta test with BRAT here: https://youtu.be/2poSS-Z91lY?t=330

**Comment by zsviczian** [comment] 2024-10-27 07:40
Any feedback on testing?

![image](https://github.com/user-attachments/assets/4e93807d-1e13-4245-9892-74e0e4d21ee6)

**Comment by zsviczian** [comment] 2024-10-27 17:25
fixed in 2.6.0

**Closed by zsviczian** 2024-10-27 17:25 UTC
Labels: Can't fix
