### ISSUE TITLE
Cursor disappear  

### ISSUE THREAD

**Issue by bagameow** [zsviczian/obsidian-excalidraw-plugin#11] opened 2021-04-21 07:23 UTC
**Describe the bug**
Cursor disappeared on VIM view mode. VIM biding is obsidian core plugin.

**To Reproduce**
- open excalidraw file to edit
- switch back to normal obsidian document
- press esc to enter vim view mode
- press esc again, cursor will disappear
- (you can press cmd + e twice to save cursor back)

**Expected behavior**
cursor should still be there.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac Bigsur
 - Version , obsidian 0.12.2 (insider build)

**Comment by zsviczian** [comment] 2021-04-21 07:31
This is going to be hard for me to test. I am completely unfamiliar with VIM. You'll need to provide me with some hand-holding to reproduce the bug. Sorry.

**Comment by bagameow** [comment] 2021-04-21 08:05
Hi , I observed that it doesn't relate to vim binding.
you can reproduce by these steps.

- open excalidraw file to edit
- switch back to normal obsidian document
- press esc key
- press esc again, cursor will disappear
(you can press cmd + e twice to save cursor back)

**Comment by bagameow** [comment] 2021-04-21 08:07
I think i can record something to reproduce this.

**Comment by bagameow** [comment] 2021-04-21 08:18
https://user-images.githubusercontent.com/9460797/115520844-251b5900-a2bd-11eb-9f43-76e3678a7b79.mov

**Comment by bagameow** [comment] 2021-04-21 08:19
after you lost the editor focus, it's easy to trigger other unexpected key (to maximize obsidian screen, etc.)

**Comment by zsviczian** [comment] 2021-04-21 08:50
I get the feeling that the root cause of this and of #12 is likely the same.
I will investigate tonight.

**Comment by bagameow** [comment] 2021-04-21 13:48
looking forward to resolving this :)

**Comment by zsviczian** [comment] 2021-04-22 06:15
This is not a production release, and it will potentially delete your drawing library within Excalidraw (not the files in your vault).
Can you test if your issue is resolved with this version?
https://github.com/zsviczian/obsidian-excalidraw-plugin/releases/tag/test1.0.4

**Comment by bagameow** [comment] 2021-04-22 10:27
yes, it's solved in test1.0.4

**Comment by zsviczian** [comment] 2021-04-22 12:39
That is great! My understanding from the Excalidraw team is they will release this version of the plugin to production in few days. I will publish the Excalidraw plugin to the community plugin store at that time.

**Closed by zsviczian** 2021-04-22 12:39 UTC
