### ISSUE TITLE
When dragging an excalidraw window independent from ob back to the OB interface, the following warning will appear（in ob V 0.15.6）

### ISSUE THREAD

**Issue by Xieleilab** [zsviczian/obsidian-excalidraw-plugin#701] opened 2022-07-15 08:37 UTC
When dragging an excalidraw window independent from ob back to the OB interface, the following warning will appear
![image](https://user-images.githubusercontent.com/78771561/179186378-aff54db8-0d48-4141-891a-40acdc17d98a.png)

**Comment by zsviczian** [comment] 2022-07-15 09:29
I am unable to reproduce this error. However, I've seen this error (unnecessarily) pop up when starting Obsidian after closing it with several popout windows open. So far I haven't been able to track down its source.

**Comment by zsviczian** [comment] 2022-08-01 16:25
I added some additional checks to only show this error when there is a real issue. Please test if 1.7.9 resolves this. 1.7.9 will be released later today.

**Comment by zsviczian** [comment] 2022-10-09 11:56
I don't recall having this error regularly pop up recently. I consider this issue resolved.

**Closed by zsviczian** 2022-10-09 11:56 UTC
Labels: bug
