### ISSUE TITLE
BUG: Hyperlink absolute paths not working

### ISSUE THREAD

**Issue by epsil0ndelta** [zsviczian/obsidian-excalidraw-plugin#1872] opened 2024-07-08 04:57 UTC
Hello, I am in the process of porting over all my drawio diagrams into the newly found Obsidian/Excalidraw ecosystem, it's a beast and I appreciate the effort! I am using Excalidraw 2.2.8 in Obsidian 1.6.5, I haven't found a mention of the following problem in the latest release notes or in other issues..

--------SYSTEM INFO:
	Obsidian version: v1.6.5
	Installer version: v1.6.5
	Operating system: Windows 10 Pro 10.0.19045
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: dark
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 2
	Plugins enabled: 2
		1: Excalidraw v2.2.8
		2: VSCode Editor v1.0.4

-------- Describe the bug
All of the functionality from hyperlinks (new tab, new tab group, new window..) as well as the _'Links will update when files are moved or renamed, if you have the Obsidian setting Files & Links/Automatically Update Internal Links enabled.'_ Seems to only work when you use the vaults item name - ex [[test]], but not when you use absolute paths that you get when right-click command _Copy Obsidian URL_ in the file explorer. the hover-CTRL preview also. In my situation, I am learning C++ and there is going to be a lot of 'Main.cpp' throughout the vault, the compilers hard coded entry point - I have to have duplicate item names, and absolute paths is the only way I know how to differentiate different links.

--------To Reproduce
1. Create two drawings, testSpoke and testHub at the top level of a vault
2. in testHub, add the text [[testSpoke]] - everything works fine
3. in testHub, add the text [[obsidian://open?vault=Vault&file=testSpoke]], from testSpoke _'Copy Obsidian URL'_
4. All functionally in description seems to break.

**Comment by zsviczian** [comment] 2024-07-12 16:12
Do not put the obsidian link in wiki link brackets. just write: `obsidian://open?vault=Vault&file=testSpoke` as the link.

However, there is a bug that I found. In case of obsidian links the link navigation only works if you click the link indicator in the top right corner. I will fix that in 2.2.9.

**Comment by zsviczian** [comment] 2024-07-12 19:23
There were a number of things not working as intended with obsidian:// links.
BTW. I do not recommend obsidian links as they will not get updated automatically if you move files around. One of the big benefits of Obsidian is how it keeps all your links intact as you move files around in your Vault. But all this does not work with obsidian:// links.
If you still want to use obsidian:// links then you have a couple of options:
- when you add it as an element link simply type `obsidian://open?vault....` as the link, do not add additional markap.
- you can also simply type the obsidian link as a text element, clicking the element will operate as a link
- you can add links as `[markdown links](obsidian://...)` this will also work.

adding an obsidian link as a `[[wiki link]]` will not work... not only in Excalidraw but in Obsidian markdown either.

That said, I now tested obsidian links and found a number of errors (no wonder since I never use these links). All the issues I found are fixed in 2.2.9.

**Closed by zsviczian** 2024-07-12 19:23 UTC
Labels: bug
