### ISSUE TITLE
BUG: dark mode error 

### ISSUE THREAD

**Issue by LEEJOOPIL** [zsviczian/obsidian-excalidraw-plugin#1066] opened 2023-03-22 08:49 UTC
hello.
I am Pilsogood living in Korea.
I am using your excalidraw plugin very well.
So, I also donated money.
The reason for sending this mail is as follows.
I use a minimal theme, but when I use this, the system is in dark mode and the menu text is not visible when excalidraw is in light mode.
Any solution?

**Comment by zsviczian** [comment] 2023-03-22 22:32
Unfortunately, this is a long ongoing conversation with the developer of the Minimal Theme. The Minimal theme includes styling that overrides Excalidraw and causes this problem. I was unable to convince @kapano to change the minimal theme :(
You can help by raising this again to bring this up on his radar until a solution is reached.
You can also choose a theme that works with Excalidraw (practically all the others).

You can find a workaround solution here: https://github.com/zsviczian/obsidian-excalidraw-plugin/issues/923#issuecomment-1479168730

Please raise an issue with the Minimal Theme to get this finally solved here: [Issues · kepano/obsidian-minimal (github.com)](https://github.com/kepano/obsidian-minimal/issues)

Closing as this is a duplicate of #923

**Closed by zsviczian** 2023-03-22 22:32 UTC
