### ISSUE TITLE
BUG: Crash on every save of Excalidraw file

### ISSUE THREAD

**Issue by devinat1** [zsviczian/obsidian-excalidraw-plugin#1680] opened 2024-04-01 22:13 UTC
**Your environment**
SYSTEM INFO:
	Obsidian version: v1.5.12
	Installer version: v1.4.16
	Operating system: Windows 10 Home 10.0.26090
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Base theme: dark
	Community theme: Minimal v7.5.3
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 54
	Plugins enabled: 25
		1: Templater v2.2.3
		2: Tab Switcher v1.4.0
		3: Google Photos v1.6.5
		4: Dataview v0.5.66
		5: Editor Syntax Highlight v0.1.3
		6: Minimal Theme Settings v7.5.0
		7: Commander v0.5.1
		8: Canvas Mindmap v0.1.9
		9: Auto Link Title v1.5.3
		10: Admonition v10.2.0
		11: Simple CanvaSearch v0.1.0
		12: QuickAdd v1.8.1
		13: Excalidraw v2.1.1
		14: Todoist Sync v1.12.0
		15: Linter v1.23.2
		16: Readwise Official v2.0.1
		17: Enhancing Export v1.10.4
		18: Zotero Integration v3.1.7
		19: Paste URL into selection v1.7.0
		20: Note Refactor v1.8.2
		21: Canvas Filter v0.9.4
		22: Ghost Fade Focus v3.0.0
		23: WakaTime v1.0.0
		24: Quick Switcher++ v4.0.0
		25: Footnote Shortcut v0.1.3

**Describe the bug**
On every save of an Excalidraw file, the entirety of Obsidian crashes.

**To Reproduce**
Save any Excalidraw file. It will crash once every 3 times on average.

**Expected behavior**
No crash

**Comment by zsviczian** [comment] 2024-04-02 06:19
I am not experiencing the same issue and unable to reproduce.
can you share more about the file you are saving? 
can you try if this happens in a test Vault with only Excalidraw?

**Comment by devinat1** [comment] 2024-04-02 16:23
This no longer happens. Perhaps the file was too large. This was the file that caused the crash on most saves:
[HA3 2024-04-01 15.12.34.excalidraw.md](https://github.com/zsviczian/obsidian-excalidraw-plugin/files/14840435/HA3.2024-04-01.15.12.34.excalidraw.md)

When I removed the very far away elements (i.e. the drawing on the upper right and bottom left corner), I believe Obsidian stopped crashing.
This was the version that had it stop crashing:
[Drawing 2024-04-02 12.20.17.excalidraw.md](https://github.com/zsviczian/obsidian-excalidraw-plugin/files/14840489/Drawing.2024-04-02.12.20.17.excalidraw.md)

It may or may not be related to removal of those elements.

**Comment by zsviczian** [comment] 2024-04-06 10:27
hm... this drawing is not that very big... 
I wonder.
I'll close this issue for now. Please reopen if you experience problems again.

**Closed by zsviczian** 2024-04-06 10:27 UTC
