### ISSUE TITLE
 parentheses in file name make the file to disappear

### ISSUE THREAD

**Issue by koenbunders** [zsviczian/obsidian-excalidraw-plugin#447] opened 2022-02-17 13:54 UTC
**Describe the bug**
Parentheses in file name make the file to disappear

**To Reproduce**
1. Creata new excalidraw picture with parentheses in its file name 
2. Klik in file viewer on the created picture
3. Klik in file viewer on another picture
Obervation: the created picture (with parentheses in its file name) gets deleted.

**Expected behavior**
The other picture would be opened while the created picture is not deleted.

**Screenshots**

**Environment (please complete the following information):**
 - OS including version: [e.g. iOS 15.1, Android 9, Windows 11, etc]
 - Plugin version: 
 - Obsidian version: 

**Additional context**

**Comment by zsviczian** [comment] 2022-03-11 20:16
I am closing this as I have received no further information. I cannot reproduce the error.
Please reopen if this is still an issue, and provide a sample filename that you are having trouble with.

**Closed by zsviczian** 2022-03-11 20:16 UTC
