### ISSUE TITLE
Palm Rejection and Pinch to Zoom a tiny bit wonky on Tablets.

### ISSUE THREAD

**Issue by notmaroun** [zsviczian/obsidian-excalidraw-plugin#325] opened 2021-12-28 12:08 UTC
Hello, I just want to preface that this plugin is absolutely amazing and has changed the way I work with Obsidian.

I've been testing Excalidraw with my tablet (Samsung Tab S7+), and to my surprise there is working touch sensitivity!

I've noticed that when I put my palm onto the tablet to write, the palm rejection works, but it draws a mini line first where i put my palm down. Likewise, when I pinch to zoom with my fingers, it draws a line between the two fingers I use to pinch, but then it works flawlessly. I was wondering if it was possible to enable a mode wherein Excalidraw will only accept inputs from styluses/pens.

**Comment by Rubiginosa** [comment] 2022-01-14 13:41
I'm on a similar device (Tab S7) and have the same request. I'm not sure if this can be done without upstream changes (there's a similar feature request on the main Excalidraw repo, I believe) but it would be a great help!

**Comment by nicocossiom** [comment] 2022-01-20 21:18
Yeah same here in my 2018 IPad Pro. The only reasonable way to zoom/move around is to go back to cursor mode and then do so. Otherwise it draws a line between the two fingers. 
I have tried in the official [excalidraw ](https://excalidraw.com/) webpage and the same happens so this is an issue that has to be fixed upstream. I just wish there was a way to only allow pencil input while drawing, like a button or something. Palm rejection works pretty well though.

**Comment by zsviczian** [comment] 2022-02-02 20:30
The issue is now resolved in 1.5.26

**Closed by zsviczian** 2022-02-02 20:30 UTC
