### ISSUE TITLE
BUG: Embed preview of drawings in markdown notes is broken starting with 2.4.0-beta-7

### ISSUE THREAD

**Issue by JoeKays** [zsviczian/obsidian-excalidraw-plugin#1956] opened 2024-08-24 10:35 UTC
**The bug**
This markdown note...:
```
![[Welcome 2024-08-24 11.51.06.excalidraw]]
```
...renders as this:
![grafik](https://github.com/user-attachments/assets/eb52f1f8-439d-45fd-b091-cf4f37434f7e)

**To Reproduce**
1. Install 2.4.0-beta-7 or above (beta-6 works as expected).
2. Create a drawing and embed it in a markdown note

**My environment**
SYSTEM INFO:
	Obsidian version: v1.6.7
	Installer version: v1.6.7
	Operating system: Windows 11 Pro 10.0.22621
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 3
	Plugins enabled: 2
		1: BRAT v1.0.1
		2: Excalidraw v2.4.0-beta-8

**I have no clue why it shows as v2.4.0-beta-8 no matter which version I install via BRAT.**

**Comment by zsviczian** [comment] 2024-08-24 11:36
indeed in beta-7 there was a change that impact rendering... but, I cannot reproduce the error.

Can you share the file that you used for your example?

**Comment by JoeKays** [comment] 2024-08-24 12:41
Interesting. These are the relevant files:

[Welcome 2024-08-24 11.51.06.excalidraw.md](https://github.com/user-attachments/files/16736643/Welcome.2024-08-24.11.51.06.excalidraw.md)
[Untitled.md](https://github.com/user-attachments/files/16736644/Untitled.md)

**Comment by zsviczian** [comment] 2024-08-25 04:51
I still can't reproduce the issue. 
I wonder if this is some combination of your settings in Excalidraw.
Does this happen with a clean new install or you have made some changes in settings?
I now created a brand new empty vault, installed Brat and -beta-9, and the examples you provided displayed correctly.
can you send me you data.json (it contains your Excalidraw settings). You will find it in `Vault-Root\.obsidian\plugins\obsidian-excalidraw-plugin` folder

<img width="814" alt="image" src="https://github.com/user-attachments/assets/b3d751e4-fd7a-4351-a833-69f6105ad6c9">

**Comment by JoeKays** [comment] 2024-08-25 08:25
Hmm, interesting. I did my testing with a clean vault without changing any settings. However, could it be that an obsidian setting is responsible for this? Or could it be a platform issue?
I will try to find a VM to do a clean install...

**Comment by JoeKays** [comment] 2024-08-25 09:11
Interestingly, I noticed that this issue is present both in edit and in view mode in my clean testing vault.
Strangely, in my main vault it is only broken in edit mode, view mode works fine... very strange.

**Comment by JoeKays** [comment] 2024-08-25 09:17
@zsviczian I did some more testing and deleted .obsidian completely again. It seems that it's always broken in edit mode but most of the time works fine in view mode. Only sometimes (I couldn't really see any pattern) it also stops working in view mode. The problem in edit mode is present both on my Windows machine and Android phone.

**Comment by zsviczian** [comment] 2024-08-26 19:54
And this is in a completely blank/new/vanilla obsidian vault? English language?... etc.
No css snippets, no additional plugins, etc.

**Comment by JoeKays** [comment] 2024-08-26 21:24
@zsviczian Just to be sure I just started from scratch on a new Android device:

I downloaded Obsidian, created a new vault, installed BRAT, installed the most recent Excalidraw Beta through BRAT, created a .md note file, called the "Excalidraw: create new drawing and embed into active document" command. Drew a rectangle and checked the .md note file - same problem, this time both in edit and in view mode.

This is the complete vault: 
[Testing.zip](https://github.com/user-attachments/files/16753857/Testing.zip)

**Comment by zsviczian** [comment] 2024-08-27 05:54
We are finally getting somewhere!

I am able to reproduce the issue on Obsidian Mobile on my Android. The same happens in my own Vault with any file... that is a good start for figuring out how Obsidian Mobile on Android is different from Desktop and from iOS. 

BUT, above you mentioned it also does not work on your Windows desktop. Can you reconfirm that? I tried your test Vault on Windows and on Mac and could not reproduce the issue.

**Comment by zsviczian** [comment] 2024-08-27 06:52
Please test with this main.js
You will need to unzip this and save it to .obsidian/plugins/obsidian-excalidraw-plugin and restart Obsidian.
[main.zip](https://github.com/user-attachments/files/16757804/main.zip)

**Comment by JoeKays** [comment] 2024-08-27 09:17
@zsviczian Awesome! It seems that this fixes the issue both on my Android and Windows device. Thank you so much 😊

**Comment by zsviczian** [comment] 2024-08-27 17:43
Fixed in 2.4.0-rc-1

**Closed by zsviczian** 2024-08-27 17:43 UTC
