### ISSUE TITLE
Inconsistent writing with iPad Pro + Pencil 

### ISSUE THREAD

**Issue by bpm323git** [zsviczian/obsidian-excalidraw-plugin#61] opened 2021-05-21 23:13 UTC
I am running Obsidian 0.0.19 and the Excalidraw 1.1.4 on a 2018 iPad Pro 11” and the Apple Pencil.

As I write and/or draw, my Pencil strokes aren’t always captured.  In previous versions, it was almost every other stroke would be captured.  That has since improved to roughly a 1:3 ratio.  I attempted to capture this in the attached screenshot.  The black strokes were captured in real time.  The red strokes were not captured, so I went back and re-drew them.  
![B7DCF98D-19CB-4B87-A127-C989B409DA52](https://user-images.githubusercontent.com/84604142/119206201-78252f00-ba68-11eb-8f38-652f41a81d00.png)

**Comment by zsviczian** [comment] 2021-05-22 07:42
So the drawing experience differs based on stroke color?
Can I ask you to test on excalidraw.com and let me know if you are experiencing the same issue? This will help me determine if the issue is with how the plugin is integrated into Obsidian, or with Excalidraw.

Please insert the following into a document in Obsidian and switch to preview mode to test:
```html
<iframe src="https://excalidraw.com" height="800" width="100%"\>
```

**Comment by bpm323git** [comment] 2021-05-22 17:58
My apologies for my poor description.  The color doesn’t make a difference.  I used red to show where the strokes did not originally show up in my writing.  

In further testing, I have found that every stroke is captured if I slow my writing down to waiting about one half to one second between strokes.  It is when I write at “normal” speeds that every other stroke is not captured.

In my attachment below, I wrote the first instance of “test” very slowly and everything was captured.  As I sped up my writing to normal speeds, strokes start to be missed.

![AF3E60FA-D162-4006-8144-FA030FC50272](https://user-images.githubusercontent.com/84604142/119236431-63e33f80-bb05-11eb-80de-0835015e3b87.png)

**Comment by zsviczian** [comment] 2021-05-22 19:21
This looks like something that unfortunately I won't be able to fix. As one last test, can you open [https://excalidraw.com](https://excalidraw.com) in a browser to see if you experience the same?

The performance will probably be better... and that is because Obsidian in the background is running a number of background processes, which aren't there in the browser when you run Excalidraw.

If it works well in the browser, then for handwriting you can use excalidraw.com, save the file and add it to obsidian manually. I'm afraid I won't be able to offer a better solution.... but I'll keep thinking about this to see if I can come up with something.

**Comment by bpm323git** [comment] 2021-05-22 20:20
I never thought to try the website itself.  I find the same behavior directly at the website in Safari, Chrome, and Firefox.  

I really appreciate all your time and apologize for the wild goose chase.  :-)

**Comment by zsviczian** [comment] 2021-05-23 04:18
Thank you for testing!

In this case, you may want to open an issue with the Excalidraw team directly. I have raised multiple topics with them and have always received very thoughtful responses and most of the time solutions in the upcoming release. They are typically releasing a new version every ~20 days... so it is usually a fast turnaround. I am keeping Obsidian Excalidraw in sync with the core component releases, so if this gets fixed on excalidraw.com, it will most likely get fixed in Obsidian as well within a few days after that.

https://github.com/excalidraw/excalidraw/issues

**Closed** 2021-05-23 04:45 UTC
Labels: Can't fix

**Comment by kevinjalbert** [comment] 2021-06-17 15:44
Just adding this here https://github.com/excalidraw/excalidraw/issues/3502
