### ISSUE TITLE
BUG: Excalidraw sync unavailable

### ISSUE THREAD

**Issue by JakubBladek** [zsviczian/obsidian-excalidraw-plugin#993] opened 2023-01-29 21:03 UTC
When I open excalidraw settings I can't see **excalidraw sync**.
I mean exactly the same what is visible on the video.Unfortunately, I can't see it.
https://youtu.be/W7pWXGIe4rQ?t=59

**Comment by zsviczian** [comment] 2023-01-29 21:31
This is an old feature. This is no longer required. At the time Obsidian sync only synchronized `.md` files and at the time the plugin did not use `.md` but `.excalidraw` files instead. By now Obsidian sync supports synchronizing all files, and also Excalidraw drawings are stored in markdown (`.md`) files, so this workaround solution is no longer required. This feature and setting was removed.

Are you using Obsidian sync? Are you experiencing some issues synchronizing Excalidraw drawings?

**Comment by JakubBladek** [comment] 2023-01-29 21:56
Hi
Thanks for your reply and efforts.
You should know that I'm very new to obsidian.

I use obsidian sync
I do experience synchronizing issues with Excalidraw drawings. After I
started using sync my drawings which previously were fine now look like this
[image: image.png]
When I switch to exclaidraw view(as shown on the warning) the drawing gets
back to normal but for short. After switching to another page and coming to
this page again drawing gets back to the state shown on the image.

By page/drawing I mean basically the same thing here.

Best
Jakub

**Comment by zsviczian** [comment] 2023-01-30 08:39
Can you run "Show Debug Info" using the Obsidian Command Palette and share the results here?

**Comment by JakubBladek** [comment] 2023-01-30 09:06
Here is debug info
![image](https://user-images.githubusercontent.com/123777150/215433696-75f97d77-9e94-4e3f-b445-56a583eae43b.png)

**Comment by JakubBladek** [comment] 2023-01-30 09:17
I also get this thing marked in red rectangle.
Pressed ctrl-f to search 76488 but without results.
![image](https://user-images.githubusercontent.com/123777150/215436039-84463d28-22af-4011-b693-bcb098f8a011.png)

**Comment by Mateusz-Grzelinski** [comment] 2023-01-30 16:51
Hi, I helped @JakubBladek  debug the issue. What most likely happened is that at some point the excalidraw json data got corrupted, so it was **always** opening as **markdown** file. When it opened as markdown, all of the other excalidrawing that you would click, would also open as markdown files, even though they were perfectly working excalidraw files. That was a point  of confusion, what lead Kuba to believe that there is something wrong with sync, as both things happened at the same time.

It is unknown how the file got corrupted. I would gues it was a misclick as you can write freely in the files, we were not able to reproduce the issue.

**Comment by zsviczian** [comment] 2023-01-30 21:05
Yes, based on the screenshot this file seems corrupted (half saved). If you need the file and you don't have a backup, I am happy to take a look to see what can be recovered. Usually a good portion...

There are two typical cases when Excalidraw files can get corrupted:
1) if Obsidian terminated (i.e. swiping away on a mobile, or closing the app on the desktop) in this situation Obsidain does not wait for the plugins to complete the save. If this happens at a wrong time files can get half saved leading to problems. With a little attention this can be avoided.
2) There are some plugins that modify markdown files, these can sometime create conflicting changes to the Excalidraw file. In this case I can see you only have the Excalidraw plugin enabled, so that is definitely not the issue here.

**Closed** 2023-02-13 12:35 UTC
