### ISSUE TITLE
Latest version, not working properly

### ISSUE THREAD

**Issue by zhl111** [zsviczian/obsidian-excalidraw-plugin#327] opened 2021-12-29 14:22 UTC
![动画](https://user-images.githubusercontent.com/29135984/147671691-35dceeb5-9ef2-4066-aa01-67fc4b312a10.gif)

**Comment by zsviczian** [comment] 2021-12-29 17:09
I tried to reproduce the error, but I couldn't.
You'll need to provide some explanation. How did you create the 4 boxes? Are these sticky notes?

**Comment by zhl111** [comment] 2021-12-30 01:01
![image](https://user-images.githubusercontent.com/29135984/147713548-2e885ba4-2fda-4dc8-981b-6a6a32a66483.png)

**Comment by zhl111** [comment] 2021-12-30 03:57
The first time is a messy text, the second time the Chinese meaning is "Keynesianism", it will be down
![动画](https://user-images.githubusercontent.com/29135984/147720533-d831a847-3d1a-47d1-9127-474d3a66b055.gif)

**Comment by zsviczian** [comment] 2021-12-30 06:20
1) What operating system are you using? Is this on iPad, on Windows, on MacOS, on Linux, on Android...?
2) Can you reproduce the error with the sticky note on https://excalidraw.com?
3) There seem to be two issues here: the StickyNote resizing, and something with an image path, but I don't see an image placeholder on your screenshot. Can you send me the Excalidraw file that is causing the issue, so I can take a look?
4) The error message seems to be related to something else yet again. Could you send a screenshot with one of the errors opened up? 
![image](https://user-images.githubusercontent.com/14358394/147726538-63cf73ad-1135-4ed1-964e-5b21efe0390e.png)

**Comment by zhl111** [comment] 2021-12-30 15:25
1，windows
2，Can't seem to reproduce the error
3，
[渐行渐远的中国红利_2021-12-30 12.41.08.excalidraw.zip](https://github.com/zsviczian/obsidian-excalidraw-plugin/files/7793590/_2021-12-30.12.41.08.excalidraw.zip)

4，
![image](https://user-images.githubusercontent.com/29135984/147764319-d3be39ec-7d1c-4eeb-863a-256a4119935d.png)
5，Console at ob startup
![image](https://user-images.githubusercontent.com/29135984/147764816-cded4dce-7e52-4630-a6f5-577fee05d018.png)

**Comment by zsviczian** [comment] 2021-12-30 17:20
I was able to reproduce the freezing issue on Excalidraw.com. I've opened issue [#4505](https://github.com/excalidraw/excalidraw/issues/4505).

Errors 4) & 5) are something different. Are you still getting those errors after updating to 1.5.10?
Seems like you are referencing a file in your drawing that no longer exists. This could be some transcluded text i.e. a text element with `![[file_that_no_longer_exists.md#^blockref]]`.

If the error is there at startup, it means it is triggered by an open Excalidraw pane in your workspace. Can you share that file as well?

**Comment by zhl111** [comment] 2021-12-30 17:36
[菲利普斯曲线_2021-12-25 21.50.31.excalidraw.zip](https://github.com/zsviczian/obsidian-excalidraw-plugin/files/7793973/_2021-12-25.21.50.31.excalidraw.zip)

**Comment by zsviczian** [comment] 2021-12-30 18:15
Please test 1.5.11 - just released

**Comment by zhl111** [comment] 2021-12-31 02:13
1, when opening excalidraw notes alone, there is no error message
2, after ctrl+open a new window, the error starts to appear
3, close the new window, the error message still rises
![动画](https://user-images.githubusercontent.com/29135984/147799066-8297d527-1b46-4537-a6e4-ba742dcf1bb2.gif)

**Comment by zhl111** [comment] 2021-12-31 12:34
The error message that appears now is the problem with this plugin:Obsidian fullscreen plugin

**Comment by zsviczian** [comment] 2022-01-01 07:25
Can we close this issue then?

**Comment by zhl111** [comment] 2022-01-01 09:33
ok，thanks

**Closed** 2022-01-01 16:06 UTC
