### ISSUE TITLE
BUG: Cannot 'Create Markdown' or 'Create Excalidraw' for file that does not exist.

### ISSUE THREAD

**Issue by koenbunders** [zsviczian/obsidian-excalidraw-plugin#1385] opened 2023-10-17 09:45 UTC
**Your environment**
SYSTEM INFO:
	Obsidian version: v1.4.16
	Installer version: v1.4.14
	Operating system: Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:43 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6000 23.0.0
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Minimal v7.3.2
	Snippets enabled: 6
	Restricted mode: off
	Plugins installed: 32
	Plugins enabled: 29
		1: Advanced Tables v0.19.1
		2: Calendar v1.5.10
		3: Carry-Forward v1.4.5
		4: Commander v0.5.0
		5: Contextual Typography v2.2.5
		6: Dataview v0.5.61
		7: Excalidraw v1.9.24
		8: ExcaliBrain v0.2.10
		9: Importer v1.4.0
		10: Kanban v1.5.3
		11: Longform v2.0.4
		12: Metadata Menu v0.5.2
		13: MetaEdit v1.8.2
		14: Natural Language Dates v0.6.1
		15: Note Refactor v1.8.2
		16: Outliner v4.8.0
		17: Paste URL into selection v1.7.0
		18: Periodic Notes v0.0.17
		19: Plugin Update Tracker v1.5.2
		20: QuickAdd v1.4.0
		21: Remember cursor position v1.0.8
		22: Sortable v0.3.1
		23: Style Settings v1.0.7
		24: Tag Wrangler v0.6.1
		25: Templater v1.16.4
		26: Tracker v1.10.9
		27: Workspaces Plus v0.3.3
		28: Minimal Theme Settings v7.3.0
		29: Supercharged Links v0.10.3

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Describe the bug**
Cannot 'Create Markdown' or 'Create Excalidraw' for file that does not exist.

**To Reproduce**
1. Create a new drawing
2. Create a link to a non existing file 
3. Click on the link
4. The dialog box 'File does not exist. Do you want to create it?' appears. 
5. Clicking the options 'Create Markdown' and 'Create Excalidraw' are nonresponsive, only option 'Nevermind' works.

**Expected behavior**
It is expected that a markdown or excalidraw file is created

**Screenshots**
![20231017 Excalidraw bug](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/12957034/a32c46f0-03e7-4215-8416-bc3cfef93c1e)

**Comment by Kenji-Takatou** [comment] 2023-10-22 03:30
The same issue occurrs for me.

I found that the bug occurs with excalidraw files that have parentheses in their names.

For instance, neither 'Create Markdown' nor 'Create Excalidraw' works with the excalidraw file named "(Studies of) Excalidraw.excalidraw," but if I rename this file to "Studies of Excalidraw.excalidraw," then both functions work as expected.

Although I'm not sure if your problem is caused by the same reason, I report this for reference.

**Comment by zsviczian** [comment] 2023-10-22 06:57
Thanks. I am able to reproduce with the parentheses in the name. I am exploring why that might be an issue.

**Comment by zsviczian** [comment] 2023-10-22 08:34
will be fixed in 1.9.25

**Closed by zsviczian** 2023-10-22 08:34 UTC

**Comment by Kenji-Takatou** [comment] 2023-10-22 08:40
Thank you! :smile:

**Comment by koenbunders** [comment] 2023-10-23 13:47
Thanks! Although in my case the bug occurred without any parentheses in the name (see screenshot OP), this update fixed it! 🙏
