### ISSUE TITLE
BUG: I get error when trying to 'Crop and Mask Image'

### ISSUE THREAD

**Issue by brianarrison** [zsviczian/obsidian-excalidraw-plugin#1546] opened 2024-01-09 11:05 UTC
**Your environment**
Please run `Command Palette/Show Debug info` in Obsidian and paste the result here.

SYSTEM INFO:
	Obsidian version: v1.5.3
	Installer version: v1.4.13
	Operating system: Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:34 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T8103 23.2.0
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 10
	Restricted mode: off
	Plugins installed: 8
	Plugins enabled: 6
		1: Recent Files v1.3.9
		2: Excalidraw v2.0.16
		3: Note Refactor v1.8.2
		4: Dataview v0.5.64
		5: ExcaliBrain v0.2.11
		6: QuickAdd v1.6.1

**Describe the bug**
When I select an image in excalidraw note and press 'crop and mask image' I get the error:

'Image did not load to the view'
New excalidraw drawing is taking too long to
load. Please try again

**Screenshots**

<img width="324" alt="image" src="https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/153327061/61be3398-dd80-44d7-8a4c-3f1505be73ae">

**Comment by zsviczian** [comment] 2024-01-09 18:08
Did you try this with multiple different images and are you always getting this result?
How large is the image you were working with? and what extension? png? jpg? webp?

**Comment by brianarrison** [comment] 2024-01-09 21:57
Hi Zsolt,

Yes I tried diff. Images and small images, both pgs and pngs

I notice that when I run the plug in it creates a file in my attachments folder called cropped_Pasted Image 20240109215240_187


I am doing something wrong? I am selecting an image that I have copied into an obsidian excalidraw file and then selecting the ‘crop and mask’ command.

Brian

**Comment by brianarrison** [comment] 2024-01-09 21:58
Yes I tried diff. Images and small images, both pgs and pngs

I noticed that when I run the plug in it creates a file in my attachments folder called cropped_Pasted Image 20240109215240_187

I am doing something wrong? I am selecting an image that I have copied into an obsidian excalidraw file and then selecting the ‘crop and mask’ command.

**Comment by zsviczian** [comment] 2024-01-10 18:09
Unfortunately, GitHub does not process image embeds via email. Your images came across as <<OBJ>>.
Could you post your response via GitHub directly? Thanks!

**Comment by brianarrison** [comment] 2024-01-10 18:21
Many thanks Zsolt,

Firstly can I take this opportunity to say how much I appreciate you for the work you do for us Obsidian users. I also really enjoy your videos. 

Here is the image I was trying to crop, in an excalidraw file:

[text excalidraw crop feature.md](https://github.com/zsviczian/obsidian-excalidraw-plugin/files/13891460/text.excalidraw.crop.feature.md)


Here is the file that got put into my attachments folder:
[cropped_Icon - Soul.md](https://github.com/zsviczian/obsidian-excalidraw-plugin/files/13891463/cropped_Icon.-.Soul.md)



If I try and open  the cropped_Pasted Image… file then all I see is the same window in which the error appeared.

Here is the dev console screenshot but I was not sure what in the dev console you wanted me to capture...

PastedGraphic-1.png

However, I set a pause on 
![PastedGraphic-1](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/153327061/585f9338-4bfe-48ad-b55a-078611b04794)
error in the dev console and noticed this:

![PastedGraphic-6](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/153327061/a6da4aee-1fbd-4a16-a95e-1ee74549fa22)

Brian

**Comment by zsviczian** [comment] 2024-01-10 18:23
could you also attach "Icon - Soul.png"

**Comment by zsviczian** [comment] 2024-01-10 18:25
and Icon - Soul.png sits in the Attachments folder as I can read in cropped? or where does it sit?

**Comment by brianarrison** [comment] 2024-01-10 18:38
I tried a different image. I still got the error message but when I selected the cropped_xxx file it let me see the image and crop it. However, the original excalidraw file was not showing the cropped image but the original. When I right clicked it I saw this:
<img width="702" alt="image" src="https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/153327061/8dff7981-648e-4b34-92ee-9bac68724152">

**Comment by zsviczian** [comment] 2024-01-10 18:41
what settings are you using for storing attachments?

![image](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/14358394/850638c2-ed3e-4b24-a29c-6ea35e2bb0ed)

Can this be a case sensitivity issue? is your Attachments folder spelled with a capital A?

**Comment by brianarrison** [comment] 2024-01-10 18:43
<img width="773" alt="image" src="https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/153327061/398dcaa6-bd54-4e18-89f4-fa8257c84239">

**Comment by brianarrison** [comment] 2024-01-10 18:44
my folder is called 'Attachments' with a capital A

**Comment by brianarrison** [comment] 2024-01-10 18:54
Why does it give me a 'second order link'? How can I make the drawing display that link? This is what the plug in seems to fail to do after it says ...taking too long...'

**Comment by zsviczian** [comment] 2024-01-10 19:04
[main.zip](https://github.com/zsviczian/obsidian-excalidraw-plugin/files/13891883/main.zip)
Can I ask you to unzip this file, copy main.js to the .obsidian/plugins/obsidian-excalidraw-plugin folder, restart obsidian and test if the issue is still there?

note: .obsidian is a hidden folder.  (Press Command+Shift+Dot to show the hidden files in  Finder)

**Comment by zsviczian** [comment] 2024-01-10 19:24
[main.zip](https://github.com/zsviczian/obsidian-excalidraw-plugin/files/13892058/main.zip)

Here's an improved .zip please test this instead.

**Comment by brianarrison** [comment] 2024-01-10 21:09
Yes Zsolt - it works with that main.js file -  the masking works too

many thanks, your are a STAR!

**Comment by zsviczian** [comment] 2024-01-10 21:10
resolved in 2.0.17

**Closed by zsviczian** 2024-01-10 21:10 UTC
