### ISSUE TITLE
Support searching for tasks defined in text boxes

### ISSUE THREAD

**Issue by wenlzhang** [zsviczian/obsidian-excalidraw-plugin#147] opened 2021-09-21 10:29 UTC
**Is your feature request related to a problem? Please describe.**
One can define tasks like `- [ ] Task` in text boxes. Such tasks are commented out when opening the drawing in Markdown mode. 
- Maybe this is why one cannot locate such tasks in the search box of Obsidian with something like `task: Task`.
- Such tasks cannot be found by the Tasks plugin either: [schemar/obsidian-tasks: Task management for the Obsidian knowledge base.](https://github.com/schemar/obsidian-tasks)

**Describe the solution you'd like**
It would be great if such tasks can be found by using native Obsidian queries and plugins like Tasks.

**Additional context**
The reason for having this feature request is that one can use Excalidraw to visually see the relationships among some crucial tasks for certain projects. Therefore, it would be great if this can be supported, from a task/project management point of view.

**Comment by zsviczian** [comment] 2021-09-21 12:03
I don't understand. It works for me. Can you share a screenshot?
![image](https://user-images.githubusercontent.com/14358394/134167086-d431865f-fd18-4e40-99a0-ec0d5adb5264.png)

**Comment by wenlzhang** [comment] 2021-09-21 12:12
As can be seen from the screenshot below, the section "Text Elements" is commented out by default.

I am using Excalidraw v1.3.10 with Obsidian v0.12.16.

![Screenshot 2021-09-21 at 14 10 40](https://user-images.githubusercontent.com/44930227/134168085-4a335e0f-2fd3-4475-bcec-20997bcbef7f.png)

**Comment by zsviczian** [comment] 2021-09-21 12:20
Wow! You are right! I did not notice that... because I am using a template that does not have the Text Element commented out. I'll fix it.

But you can fix it yourself as well immediately.
- create a blank drawing. Name it "Template.excalidraw" or what ever you like
- open it in Markdown view and delete the comment before the Text Elements section
- Open excalidraw settings, and specify your template 
- New drawings will use this template and won't have Text Elements commented out.
![image](https://user-images.githubusercontent.com/14358394/134169217-f02e9174-b9bf-48c9-9bd3-bddffc658628.png)

**Comment by wenlzhang** [comment] 2021-09-21 12:37
Thanks for the explanation!

Defining a template file like this works for me. 😃

**Comment by zsviczian** [comment] 2021-09-21 17:20
Root cause is resolved in [1.3.11](https://github.com/zsviczian/obsidian-excalidraw-plugin/releases/tag/1.3.11)

**Closed by zsviczian** 2021-09-21 17:20 UTC
