### ISSUE TITLE
BUG: Excalidraw stopped working on the tablet after the update

### ISSUE THREAD

**Issue by GardarikanetS** [zsviczian/obsidian-excalidraw-plugin#1598] opened 2024-02-19 07:57 UTC
**Your environment**
SYSTEM INFO:
	Operating system: android 12 (HUAWEI DBY-W09)
	Obsidian version: 1.4.16 (114)
	API version: v1.4.16
	Login status: not logged in
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 1
	Plugins enabled: 0

RECOMMENDATIONS:
	none

From me:
Matepad 11 (2021)
resolution 2560:1600(16:10)

**Describe the bug**
After one of the latest updates excalidraw stopped turning on on my tablet. 
Error failed to load plugin obsidian-excalidraw-plugin
Tested on new empty vault
On my phone, poco x3 pro, everything works as before

**To Reproduce**
1. Download plugin
2.Try turning it on

**Expected behavior**

**Screenshots**
![Screenshot_20240219_135309_md obsidian](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/101533106/4033905a-a039-4c2e-bdec-11619340150e)
![Screenshot_20240219_135318_md obsidian](https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/101533106/032751d6-15f9-47e4-92a5-c099d1d5062d)

**Comment by zsviczian** [comment] 2024-02-19 17:06
likely related: #1525

While in the next update I am trying to address this with a complete recompiling with Node 18, I can't guarantee that will solve your issue.

Please update the android webview component to the newest version.

**Comment by GardarikanetS** [comment] 2024-02-20 00:15
So, after the update, the problem didn't go away. When I tried to update webview I was surprised to find out that it was not even installed on the tablet 🤔. This is probably due to the fact that the manufacturer is huawei, which doesn't have google services at all. Anyway, I installed them and it didn't solve the problem. The only thing I can do is to upgrade to a newer harmonyOS (3.0.0 instead of the current 2.0.0). I will do that within 24 hours, after which I will post here

**Comment by khaled-magdy123** [comment] 2024-02-20 04:28
> I just released 2.0.21 - which is a complete rebuild with an older version of Node. Can you test if 2.0.21 works for you?
> 
> Else I still recommend updating your WebView component.

I have the same issue with huawei phone 😞

**Comment by blkdark** [comment] 2024-02-20 15:20
> > I just released 2.0.21 - which is a complete rebuild with an older version of Node. Can you test if 2.0.21 works for you?
> > Else I still recommend updating your WebView component.
> 
> I have the same issue with huawei phone 😞

The same issue with my tablet Huawei M6 mediapad 😩

**Comment by zsviczian** [comment] 2024-02-21 17:52
please test 2.0.22
I tested the load issue to be fixed on iOS 15 or older #1525 
Since this is related to javascript version support I can imagine the fix also solves your problem as well. Please let me know.

**Comment by blkdark** [comment] 2024-02-22 03:42
> please test 2.0.22 I tested the load issue to be fixed on iOS 15 or older #1525 Since this is related to javascript version support I can imagine the fix also solves your problem as well. Please let me know.

Hi. Everything now works perfectly on my Huawei tablet. Thank you. 😎

**Comment by GardarikanetS** [comment] 2024-02-22 06:01
> пожалуйста, протестируйте 2.0.22 Я тестировал, что проблема с загрузкой будет исправлена на iOS 15 или более поздней версии [# 1525](https://github.com/zsviczian/obsidian-excalidraw-plugin/issues/1525) Поскольку это связано с поддержкой версий javascript, я могу предположить, что исправление также решает вашу проблему. Пожалуйста, дайте мне знать.

Hi. It works, THANKS

**Comment by GardarikanetS** [comment] 2024-02-22 06:02
Version 2.0.22 solved this problem

**Closed** 2024-02-22 06:53 UTC

**Comment by blkdark** [comment] 2024-02-28 04:06
Hello. The problem reappeared with the latest plugin update on my Huawei mediapad m6 😟.

**Comment by zsviczian** [comment] 2024-02-28 06:55
I am sorry about that.

This is down to javascript language support and the version of javascript the code being built requires. Seems Huawei is shipping their devices with dated language support.

The issue is the component that was causing the issue between 2.0.17 and 2.0.22 did not change with 2.0.23.

The problem is that the issue does not come from my own code, but from imported libraries, which continue to change... and I cannot fork and rebuild each library that causes such problems, like I did in 2.0.22.

I did test 2.0.23 on my old iPad with iOS 15.7 and it worked without issues. I don't have a version of your environment, thus can't test to find out which component and what might have changed. As of now, I don't see a solution for you.

**Comment by wjixiang** [comment] 2024-05-08 11:26
This method only worked before Obsidian 1.5...😭

**Comment by zsviczian** [comment] 2024-05-08 11:33
You can also download and configure Web View component.

------ 

Here's a step-by-step guide generated by chat GPT about installing a different web view component on Android, using Chrome Beta as an example:

1. **Download Chrome Beta**: First, go to the Google Play Store on your Android device and search for "Chrome Beta." Once you find it, tap on the "Install" button to download and install Chrome Beta on your device.
2. **Enable Developer Options**: Go to your device's Settings menu. Scroll down and find the "About phone" or "About device" option. Tap on it, then find the "Build number" entry. Tap on "Build number" repeatedly (usually about 7 times) until you see a message saying that Developer Options have been enabled.
3. **Access Developer Options**: Now, go back to the main Settings menu. You should see a new option called "Developer options" or "Developer settings." Tap on it to enter the Developer Options menu.
4. **Enable WebView implementation selection**: Scroll down in the Developer Options menu until you find an option labeled "WebView implementation" or something similar. Tap on it to open the WebView implementation settings.
5. **Select Chrome Beta as WebView**: In the WebView implementation settings, you should see an option to select the web view provider. Tap on it and choose "Chrome Beta" from the list of available options.
6. **Confirm Selection**: After selecting Chrome Beta as the WebView provider, you may be prompted to confirm your choice. Follow the on-screen instructions to confirm your selection and set Chrome Beta as the default WebView provider on your device.
7. **Restart Your Device**: Once you've confirmed the selection, restart your device to apply the changes.

After following these steps, Chrome Beta should be installed as the WebView component on your Android device. Keep in mind that the exact steps may vary slightly depending on your device's manufacturer and Android version.

**Comment by sanabel-al-firdaws** [comment] 2024-07-07 15:16
i am on a Huawei phone and followed what you did and it didn't work because huwaui didn't let me change the web view after going to dev settings

the thing that worked was checking if i had the latest version of huwaui web view huwaui gallary installed an old version go to apkmirror and download the latest version

**Comment by asdfghzxc12** [comment] 2024-10-01 18:47
I used machine translation when writing this paragraph, so it may not be very accurate
My Huawei M6 tablet has solved this problem by updating Huawei WebView, which is a link to the new Huawei WebView: https://www.apkmirror.com/apk/huawei/huawei-webview-2/

**Comment by zsviczian** [comment] 2024-10-02 05:43
@asdfghzxc12, Thanks for sharing!
