### ISSUE TITLE
Transcluded block with a parent bullet does not embed sub-bullets

### ISSUE THREAD

**Issue by ryanwwest** [zsviczian/obsidian-excalidraw-plugin#853] opened 2022-10-20 18:30 UTC
**Describe the bug**

A transcluded block link with a parent bullet does not display embedded sub-bullets within Excalidraw, which is contrary to default Obsidian behavior.

**To Reproduce**

1. Create a parent bullet and child bullets
2. Create a block reference link to the _parent bullet_
3. Transclude the link (using `!` before said link) in Excalidraw (I did this within a Rectangle). Possibly reload Excalidraw to update link.
4. Observe that only the parent bullet is visible, not child bullets.

**Expected behavior**

Both the parent bullet and any children (and sub-children) bullets should be displayed within Excalidraw if transcluding that block.

**Screenshots**

Here is an example parent bullet point with two sub-bullets, whose parent block can be referenced using the `^` character. Note that the Obsidian default embedded transclusion immediately below it shows both child bullet points. 
![image](https://user-images.githubusercontent.com/31378238/197028416-4a36d684-e8a2-46ba-8402-1733c6518f43.png)

Here is the same block transcluded in a Excalidraw rectangle. Note that only the parent bullet point is displayed, even though the same embed link is used in both places: 
![image](https://user-images.githubusercontent.com/31378238/197028098-da769c1b-718d-44b3-a5c1-ad8fe7e27a72.png)

**Environment (please complete the following information):**
 - OS including version: MacOS Monterey 12.6
 - Plugin version: 1.7.25
 - Obsidian version: 1.0.1

**Comment by zsviczian** [comment] 2022-10-24 16:30
I am able to reproduce.
I am also thinking that if I transclude the entire document, then I should hide the `^block_references` from the end of the paragraphs.

**Comment by ryanwwest** [comment] 2022-10-24 16:32
I think that hiding them would make sense; it seems that this is already the Obsidian default for transcluding.

**Comment by zsviczian** [comment] 2022-10-24 18:57
This looks better. I'll be testing the change for a few days to make sure it doesn't have unintended side effects

![image](https://user-images.githubusercontent.com/14358394/197604105-cbbce55c-c4f6-47ec-a0fe-59e738624af1.png)

**Comment by zsviczian** [comment] 2022-10-24 19:02
Should you also want to test the change you can replace the main.js in your `.obsidian/plugins/obsidian-excalidraw-plugin` folder to the one attached here. Don't forget to unzip.

[main.zip](https://github.com/zsviczian/obsidian-excalidraw-plugin/files/9854546/main.zip)

**Comment by zsviczian** [comment] 2022-10-29 10:43
To be released in 1.7.26

**Closed by zsviczian** 2022-10-29 10:43 UTC
Labels: enhancement

**Comment by ryanwwest** [comment] 2022-11-01 16:41
Thank you!
