### ISSUE TITLE
BUG: crash on ipad when artboard shrinks to 30%

### ISSUE THREAD

**Issue by Noyamo** [zsviczian/obsidian-excalidraw-plugin#1005] opened 2023-02-03 13:23 UTC
**Your environment**
SYSTEM INFO:
	Operating system: ios 16.2 (Apple iPad)
	Obsidian version: 1.4.1 (83)
	API version: v1.0.3
	Login status: not logged in
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 2
	Plugins enabled: 2
		1: Remotely Save v0.3.25
		2: Excalidraw v1.8.12

**Describe the bug**
obsidian crashing on ipad! excalidraw's artboard shrinks to 30% and obsidian crashes! The screen is stuck. I can't manipulate anything. Just write a little more ,file size up to 2mb, shrink the artboard to 30%, showing more content, and crash! The device is the ipad2021pro， should not be low hardware performance, but a software problem. Device replacement test, Android and Windows did not crash. Only the ipad crashed. Can the administrator give feedback to fix this bug? Thank you very much

**To Reproduce**
1. write a little more ,file size up to about 2mb
2. to show more content,shrink the artboard to 30% or smaller
3. crash! The screen is stuck. I can't manipulate anything

**Comment by zsviczian** [comment] 2023-02-07 20:09
This looks like related to this known issue: https://github.com/excalidraw/excalidraw/issues/5788
It only happens when you have a larger number of handwritten strokes.

Unfortunately, the issue is caused by a javascript feature (the Canvas object) used by Excalidraw, that is not adequately supported on iOS/Safari. The issue has been open for a while. I've already spent about 8-10 hours trying to debug and fix the issue, but because Apple does not allow iPad debugging from Windows or Linux I was not able to get to the bottom of the issue... and developers with Mac OS access haven't picked this issue up. In short, the only way to avoid the issue from freezing your iPad is to limit amount of handwriting, and/or to avoid zooming out. Sorry.

**Comment by zsviczian** [comment] 2023-02-09 11:50
This is the same issue as #938. I will close this and track the issue there.

**Closed by zsviczian** 2023-02-09 11:50 UTC
Labels: Can't fix, Apple/Safari deficiency
