### ISSUE TITLE
Stuck in Zoom and Pane mode

### ISSUE THREAD

**Issue by Avanonyme** [zsviczian/obsidian-excalidraw-plugin#709] opened 2022-07-21 19:44 UTC
**Describe the bug**
Everytime I work in a excalidraw drawing in Obsidian with my Veikk s640 pencil and tablet the drawing seems to get stuck in some sort of zooming mode after ~20 minutes. Apparently other type of drawing tablets works too to reproduce the bug, see https://github.com/excalidraw/excalidraw/issues/3553. I didn't try any of the solutions proposed in that issue because I was not sure if the Obsidian version would work the same.

**Environment:**
 - MacBook Pro 2021 16 inch macOS Monterey
 - Plugin version: Excalidraw 1.7.8, ExcaliBrain 0.1.4
 - Obsidian version: 0.15.6

Here's a video to show what I'm saying 
https://drive.google.com/file/d/1-e8w8SwMKYed0tiVqAycuEsydMIOcKVj/view?usp=sharing
(the bug begins at :30)

**Comment by zsviczian** [comment] 2022-07-22 05:18
The Obsidian version very closely follows the excalidraw.com version. I see the issue you are referring to was closed a long time ago, thus I would expect that the related fixes have been deployed to code.

Question: can you reproduce the same error on excalidraw.com?

I’ll also try to reproduce, though I don’t have an external pen, only a Samsung Note with an SPen and an iPad with a Pencil. Not sure the same bug can be achieved.

However, based on the video I have some ideas where to look for such an error. The only thing is I am traveling without access to my development environment, so I won’t be able to get to this for another few weeks… sorry.

**Comment by Avanonyme** [comment] 2022-07-26 20:43
Thank you for the quick answer. I was able to reproduce the bug in the web version of excalidraw. Should I open an issue on their repository as well?

**Comment by zsviczian** [comment] 2022-08-01 15:30
Sorry for the delay in answering. I was away on holiday with limited access to github. Yes, please open an issue for this on the main Excalidraw github issue list:

https://github.com/excalidraw/excalidraw/issues

**Comment by zsviczian** [comment] 2022-10-09 12:11
Hi @Avanonyme Is this still a problem? Have you opened a new issue for this with Excalidraw? I did not see it linked here.

Since you can reproduce the issue on excalidraw.com, I will close this issue, since the solution needs to be found in the main product and not the obsidian plugin.

**Closed by zsviczian** 2022-10-09 12:11 UTC
Labels: bug, transfer to excalidraw.com
