### ISSUE TITLE
Can‘t insert an image on ipad

### ISSUE THREAD

**Issue by ih8snow** [zsviczian/obsidian-excalidraw-plugin#584] opened 2022-04-13 16:09 UTC
**Describe the bug**
When I click on the insert image icon (9), I don‘t see the icons that should help me to find the image on my ipad. Works when I use the Browserversion of Excalidraw.

![FE3162E4-9785-49DE-98DD-509CC59745F7](https://user-images.githubusercontent.com/82544852/163223564-38af7172-2320-4561-af11-b22b59883d1b.jpeg)

**Comment by zsviczian** [comment] 2022-04-13 20:55
The good news: I am able to reproduce the issue on the iPad. The bad news: this feature works without problems on my Android… which is a bummer, because I don’t have a debugger for the iPad. Until now I got away with debugging problems on Android. Based on my research to date, unfortunately Apple does not support debugging iOS from Windows. I’ll see what I can do, but as of now, I have no idea how I’ll get to the bottom of this.

**Comment by zsviczian** [comment] 2022-04-13 20:58
> Works when I use the Browserversion of Excalidraw.

Are you sure about this? it does not work for me.
Which is good news, because then this is not an Obsidian Plugin issue. I’ll raise an issue with Excalidraw now.

**Comment by ih8snow** [comment] 2022-04-15 04:40
> Are you sure about this? it does not work for me.

You are correct. It does not work. I did not try fully, just saw the icons without trying to use an image.
Does not work from the image lib. or taking a new image.
So let's see :-)

**Comment by zsviczian** [comment] 2022-04-16 13:10
Fixed in 1.6.25. I will release it later today.

**Closed by zsviczian** 2022-04-16 13:10 UTC
