### ISSUE TITLE
BUG: Text Flickering in Container while typing - Install beta to receive fix early

### ISSUE THREAD

**Issue by fiwesystems** [zsviczian/obsidian-excalidraw-plugin#2015] opened 2024-09-10 09:07 UTC
### Have you searched for existing issues (including closed ones)?

- [ ] Yes, I have searched the existing issues.

### Does this bug persist in a new vault with only Excalidraw installed?

- [ ] Yes, I have verified the issue persists.

### Your environment

This occurred for me in the latest version so it seems like a regression. 
Here is a video of the issue: https://www.dropbox.com/scl/fi/su3atf20hh0lmel1beem7/ExcalidrawBug.mov?rlkey=59wpwk1fs39ppxm376i9w1u8h&dl=0
The only thing I've tried is to restart Obsidian. 

### Describe the bug

Please see this video recording.
https://www.dropbox.com/scl/fi/su3atf20hh0lmel1beem7/ExcalidrawBug.mov?rlkey=59wpwk1fs39ppxm376i9w1u8h&dl=0

### Steps to reproduce

1. Create a text box
2. Start typing

**Comment by zsviczian** [comment] 2024-09-10 17:02
The issue had nothing to do with Font Magic in Excalidraw. Indeed I created the regression when addressing canvas shift when typing near the right side of the canvas at high zoom values...

The issue is fixed in [2.5.0-beta-2](https://github.com/zsviczian/obsidian-excalidraw-plugin/releases/tag/2.5.0-beta-2). It is unlikely that I will release this fix to public soon. There have been too frequent releases recently and I know people will get anxious of the many updates - even if they are just tiny changes. This is the drawback of the Obsidian model, on Excalidraw.com you do not notice the daily deployments :(

If you'd like to have the bug fixed before the next public release you can install 2.5.0-beta-2 using BRAT. This video explains how to configure [BRAT for Excalidraw](https://youtu.be/2poSS-Z91lY?si=xhU9rE4-9iPbWd2h&t=330)

**Comment by fiwesystems** [comment] 2024-09-11 09:30
Thank you for so quickly addressing this bug.
I installed the Beta and can confirm that it solves the problem. A restart of Obsidian was required before the fix took effect on files that was already open.

Regarding the decision to delay the update, it could make sense to do so based on how many users are affected by the issue. But it was kind of hard to work in Excalidraw at all with the problem being present. This is because you cannot see properly what you are typing. So if it is a large number of users I would perhaps reconsider this.

**Comment by zsviczian** [comment] 2024-09-11 09:38
yeah... I am also considering to ditch the monthly update approach. The more changes packed into a release the higher likelihood of something breaking. One reason for having so frequent releases is to minimize the impact of each release and help me quickly find what has caused the feature to break....

**Comment by zsviczian** [comment] 2024-09-11 09:41
btw -beta-2 comes with a different flickering of its own... which I've fixed since and will release as beta-3 later tonight. https://github.com/excalidraw/excalidraw/issues/8489

This is the challenge and thrill of building a bridge between two ever evolving islands Obsidian and Excalidraw. New features and evolution come at a price.

**Comment by zsviczian** [comment] 2024-09-13 16:32
fixed in 2.5.0

**Closed by zsviczian** 2024-09-13 16:32 UTC
Labels: bug
