### ISSUE TITLE
Cannot Drag and Drop Images

### ISSUE THREAD

**Issue by fitzagard** [zsviczian/obsidian-excalidraw-plugin#304] opened 2021-12-19 01:29 UTC
**Describe the bug**
The Excalidraw plugin prevents the native drag-n-drop functionality of images into Obsidian. However, drag-n-drop into the excalidraw canvas works. This may be related to #283 

**To Reproduce**
1. Enable Excalidraw
2. Open a regular md file
3. Try to drag an image from desktop to regular Obsidian .md file
4. Image is not accepted

**Expected behavior**
The image should be automatically embedded into md file. If excalidraw is disabled drag-n-drop works as expected

**Desktop (please complete the following information):**
 - OS: macOS Monterey
 - Obsidian Version v0.13.12
 - Installer version v0.12.3

**Comment by zsviczian** [comment] 2021-12-19 12:03
I was able to reproduce the issue. I am in the middle of some changes with Excalidraw... which means it will take a couple of days before I am able to release a fix for this.

Thanks for raising the issue!

**Comment by zsviczian** [comment] 2021-12-20 09:48
Fixed with: https://github.com/excalidraw/excalidraw/pull/4445 waiting for deployment

**Comment by zsviczian** [comment] 2021-12-23 19:19
fixed in 1.5.4

**Closed** 2021-12-23 19:20 UTC
Labels: bug

**Comment by fitzagard** [comment] 2021-12-23 23:49
Thanks for such a fast turnaround fix for the bug! Awesome work!

**Comment by miluoshi** [comment] 2022-02-09 18:01
@zsviczian  This is happening for me again in the latest version.

I can't drag-n-drop any image or drawing from file explorer using CMD + drop (MacOS).
When I drag-n-drop without CMD, it includes a link to a file in the drawing, but CMD does nothing.

If I type `![[filename]]` for any existing image file in the drawing and turn on preview mode, file contents as text instead of original image are displayed. 
I've tried it with svg, png and excalidraw files. 

![image](https://user-images.githubusercontent.com/1130547/153261568-57229f23-f039-44f6-85ab-4966b3a61e13.png)


**Desktop (please complete the following information):**

OS: macOS Monterey
Obsidian Version v0.13.24
Installer version v0.12.5
Excalidraw version: 1.6.5
Theme: Default
All other plugins turned off and Obsidian restarted before testing.

**Comment by zsviczian** [comment] 2022-02-09 22:12
Did it work before 1.6.5?
Did you install any other Obsidian plugins in the meantime?
Can you try turning off the other plugins to see if the issue is not caused by another plugin?

**Comment by miluoshi** [comment] 2022-02-10 08:30
> OS: macOS Monterey
Obsidian Version v0.13.24
Installer version v0.12.5
Excalidraw version: 1.6.5
Theme: Default
> **All other plugins turned off and Obsidian restarted before testing.**

I've tried it with other plugins turned off.

> Did it work before 1.6.5?

I don't remember, I think I haven't tried it in previous versions. Do you want me to test it in older version?

**Comment by zsviczian** [comment] 2022-02-10 09:10
Just to confirm, when all the plugins were off, you still weren't able to drag and drop.
Try dragging and only pressing cmd right before dropping the image. Does that help?

Regarding your previous comment:
The `![[filename]]` does not work for images in Excalidraw.

Does the command palette action: `Excalidraw: Insert image from vault` work for you?

**Comment by zsviczian** [comment] 2022-02-14 18:15
1) Do you see any errors on the developer console? (CMD+Shift+i)

2) Can you also confirm that you get `null` as the result when you execute the following command in the developer console:
`ExcalidrawAutomate.onDropHook`
![image](https://user-images.githubusercontent.com/14358394/153922279-98dee9b6-8c44-470e-a527-142a8db2fe82.png)

**Comment by zsviczian** [comment] 2022-02-15 09:48
I am starting to run out of ideas... we may end up having to do a short zoom call over the weekend.

Does drag&drop work in other parts of Obsidian? e.g. dropping a file from file explorer into a markdown document?
What happens if you create a blank Vault with Excalidraw. Does drag&drop work in that case?

**Comment by miluoshi** [comment] 2022-02-15 10:06
Thanks for your help, by the way!

I'll try it once more with clean Obsidian installation and blank Vault. Just to be sure that I'm testing it correctly: I should be able to drag&drop both Excalidraw drawings and supported image files (e.g. jpg, png) while holding `cmd` on Mac into Excalidraw canvas to embed those images, right?

> Does drag&drop work in other parts of Obsidian? e.g. dropping a file from file explorer into a markdown document?
It works in markdown documents - dropping another md file inserts a wikilink and dropping of an image embeds it with `![[ ]]` link in the document.

**Comment by zsviczian** [comment] 2022-02-15 11:04
Please execute this command in Developer Console:
`ExcalidrawAutomate.onDropHook = (data) => console.log(data, {meta: data.event.metaKey, ctrl: data.event.ctrlKey, alt: data.event.altKey, shift: data.event.shiftKey});`

Then try to CMD + Drop a file into Excalidraw

Then do a screenshot, opening the result set as you see on screenshot below
i.e. not this:
![image](https://user-images.githubusercontent.com/14358394/154049472-f94bf5c4-0688-4f22-8e3f-a753251e2b69.png)

but this:

![image](https://user-images.githubusercontent.com/14358394/154049154-6cf21820-e97b-4e12-8c1a-b15fbc6687c4.png)

**Comment by zsviczian** [comment] 2022-02-18 07:08
@miluoshi, I wanted to follow up on your issue. Let me know if you need any help with the debug instructions from 3 days ago.

**Comment by miluoshi** [comment] 2022-02-20 19:42
@zsviczian sorry, I was busy in last days. 

I've tried it with blank Vault. On drop without CMD, the `onDropHook` logs some data, but while holding CMD, there's no drop event. I've tried `document.ondrop` event handler with `document.ondrop = (e) => console.log(e)`, but it is not fired at all on CMD + drop. 

It seems like either Obsidian, or maybe some system settings prevent drop event while holding CMD. I'll try it once more with  new macOS user.

**Comment by miluoshi** [comment] 2022-02-20 22:33
I found this in Discord:
> Yeah... It's stupid but Apple decided that we can't handle modifier+drag ourselves 
> They do something for us and we never get the event that the drop happens
> Yeah in my testing only shift you can hold while dropping so we can get the event, sometimes ctrl. Command and option are both hooked for some system level action which doesn't do anything for us
> https://discord.com/channels/686053708261228577/716028884885307432/812539048816017431

That would explain why drop didn't work for me at all with cmd modifier key. Maybe dropping images/drawings into canvas never worked for Obsidian in Macos...

**Comment by zsviczian** [comment] 2022-02-21 06:44
So we have two options. I can change CMD to SHIFT, then it will be shift drag.
I can also write a short script and place it in the script store to convert links to images. i.e. you drop a link to a file, and then press a hotkey and it is converted in to an image.

Before I implement the SHIFT option, it would be great if you could do the testing explained [above](https://github.com/zsviczian/obsidian-excalidraw-plugin/issues/304#issuecomment-1040139386). Please do the testing 3 times. Holding in one case the SHIFT, in the other the CTRL, and finally the CMD button. Please send me the 3 result screenshots from developer console.

**Comment by miluoshi** [comment] 2022-02-21 10:59
Here are payloads for CTRL+drop and SHIFT+drop. For CMD and ALT modifier keys there is no event received. In order to be able to use CTRL modifier key, it has to be pushed after `drag` event, otherwise CTRL+left mouse opens context menu in file  explorer. Also SHIFT+drag does not work in this order. It has to be first drag and then SHIFT.

![image](https://user-images.githubusercontent.com/1130547/154941463-3b2e830d-a404-49a2-b8da-92bfb041dcaa.png)

Using SHIFT to insert images would be great solution.
