### ISSUE TITLE
BUG: Modified LaTex formulas still display the original content

### ISSUE THREAD

**Issue by nongzhenyu** [zsviczian/obsidian-excalidraw-plugin#2105] opened 2024-11-06 18:29 UTC
### Have you searched for existing issues (including closed ones)?

- [X] Yes, I have searched the existing issues.

### Does this bug persist in a new vault with only Excalidraw installed?

- [X] Yes, I have verified the issue persists.

### Your environment

SYSTEM INFO:
	Obsidian version: v1.7.5
	Installer version: v1.5.11
	Operating system: Windows 10 Pro 10.0.22631
	Login status: not logged in
	Language: zh
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 1
	Plugins enabled: 1
		1: Excalidraw v2.6.5

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

### Describe the bug

Updated from v2.6.2 to v2.6.5, modifying LaTeX formulas still displays the original content, and the file must be closed and reopened to display the modified content.

**Comment by zsviczian** [comment] 2024-11-07 10:07
I am able to reproduce.
This is why I don't like to build features that I do not use. I simply don't notice it is broken.
Will fix it.

**Comment by zsviczian** [comment] 2024-11-07 19:27
Fixed in 2.6.6
Caused by [#8730](https://github.com/excalidraw/excalidraw/pull/8730)

**Closed by zsviczian** 2024-11-07 19:27 UTC
Labels: bug
